/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.JDBC;
import java.awt.Desktop;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasitha Udara
 */
public class GuardianRegistration extends javax.swing.JFrame {

    public GuardianRegistration() {
        initComponents();
        Menu();
        lbl_username.setText(Home.un);
        lbl_userType.setText(Home.ut);
        loadTblguardianreg();
        tcl.setGuardianId(txt_id);
        new Classes.Commons().background(this, lbl_background);
        cmb_salutation.grabFocus();
        lbl_date.setText(new Classes.Commons().Date());
        new Classes.Commons().time(lbl_time);
    }

    JDBC db = new JDBC();
    int sr;
    Classes.ToolsClass tcl = new Classes.ToolsClass();
    String salutation, type;
    static String selectGuardian = "";
    static boolean gurRegd = false;
    
     //////------------Menu-----------//////

    void Menu() {
        try {
            popup_menu.setText("Menu");
            popup_help.setText("Help");
            popup_exit.setText("Exit");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        popup_menu = new javax.swing.JMenuItem();
        popup_help = new javax.swing.JMenuItem();
        popup_exit = new javax.swing.JMenuItem();
        pnl_background = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        lbl_userType = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_guardianDetails = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        lbl_salutation = new javax.swing.JLabel();
        lbl_lastName = new javax.swing.JLabel();
        lbl_type = new javax.swing.JLabel();
        lbl_homeNumber = new javax.swing.JLabel();
        lbl_mobileNumber = new javax.swing.JLabel();
        lbl_firstName = new javax.swing.JLabel();
        txt_mobileNumber = new javax.swing.JTextField();
        txt_homeNumber = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        cmb_type = new javax.swing.JComboBox();
        cmb_salutation = new javax.swing.JComboBox();
        txt_firstName = new javax.swing.JTextField();
        pnl_search = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnl_details = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_guardianDetails = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        popup_menu.setText("jMenuItem1");
        popup_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menuActionPerformed(evt);
            }
        });
        popupMenu.add(popup_menu);

        popup_help.setText("jMenuItem1");
        popup_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_helpActionPerformed(evt);
            }
        });
        popupMenu.add(popup_help);

        popup_exit.setText("jMenuItem3");
        popup_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_exitActionPerformed(evt);
            }
        });
        popupMenu.add(popup_exit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));
        pnl_background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_backgroundMouseClicked(evt);
            }
        });
        pnl_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_header.setBackground(new java.awt.Color(255, 255, 255));
        pnl_header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_headerMouseClicked(evt);
            }
        });
        pnl_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        btn_close.setContentAreaFilled(false);
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        pnl_header.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 16, 16));

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        pnl_header.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 32, 32));

        lbl_userType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_userType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_userType.setText("User type");
        pnl_header.add(lbl_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 220, -1));

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_username.setText("Username");
        pnl_header.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 220, -1));

        lbl_time.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_time.setText("jLabel3");
        pnl_header.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 23, 100, -1));

        lbl_date.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_date.setText("jLabel3");
        pnl_header.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Guardian Registration");
        pnl_header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 340, 30));

        pnl_background.add(pnl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1116, 50));

        pnl_guardianDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guardian Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_guardianDetails.setOpaque(false);
        pnl_guardianDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_guardianDetailsMouseClicked(evt);
            }
        });

        lbl_id.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_id.setText("Guardian ID:");

        lbl_salutation.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_salutation.setText("Salutation:");

        lbl_lastName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_lastName.setText("Last Name:");

        lbl_type.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_type.setText("Type:");

        lbl_homeNumber.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_homeNumber.setText("Home Number:");

        lbl_mobileNumber.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_mobileNumber.setText("Mobile Number:");

        lbl_firstName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_firstName.setText("First Name:");

        txt_mobileNumber.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_mobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mobileNumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mobileNumberKeyTyped(evt);
            }
        });

        txt_homeNumber.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_homeNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_homeNumberFocusLost(evt);
            }
        });
        txt_homeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_homeNumberKeyTyped(evt);
            }
        });

        txt_lastName.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lastNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastNameKeyTyped(evt);
            }
        });

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_id.setEnabled(false);
        txt_id.setOpaque(false);

        cmb_type.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Parent", "Guardian" }));
        cmb_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmb_typeKeyTyped(evt);
            }
        });

        cmb_salutation.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cmb_salutation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr", "Mrs", "Miss", "Rev" }));

        txt_firstName.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_firstNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstNameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnl_guardianDetailsLayout = new javax.swing.GroupLayout(pnl_guardianDetails);
        pnl_guardianDetails.setLayout(pnl_guardianDetailsLayout);
        pnl_guardianDetailsLayout.setHorizontalGroup(
            pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_guardianDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_mobileNumber)
                    .addComponent(lbl_homeNumber)
                    .addComponent(lbl_salutation)
                    .addComponent(lbl_id)
                    .addComponent(lbl_lastName)
                    .addComponent(lbl_type)
                    .addComponent(lbl_firstName))
                .addGap(36, 36, 36)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_salutation, 0, 296, Short.MAX_VALUE)
                    .addComponent(txt_homeNumber)
                    .addComponent(txt_mobileNumber)
                    .addComponent(txt_lastName)
                    .addComponent(txt_id)
                    .addComponent(cmb_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_firstName))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnl_guardianDetailsLayout.setVerticalGroup(
            pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_guardianDetailsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_salutation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_salutation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_firstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_lastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_type)
                    .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mobileNumber)
                    .addComponent(txt_mobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_guardianDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_homeNumber)
                    .addComponent(txt_homeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pnl_background.add(pnl_guardianDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, -1, 354));

        pnl_search.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_search.setOpaque(false);
        pnl_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_searchMouseClicked(evt);
            }
        });

        txt_search.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_search.setToolTipText("Search By Guardian Name");
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Search By First Name");

        javax.swing.GroupLayout pnl_searchLayout = new javax.swing.GroupLayout(pnl_search);
        pnl_search.setLayout(pnl_searchLayout);
        pnl_searchLayout.setHorizontalGroup(
            pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_searchLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_searchLayout.setVerticalGroup(
            pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_searchLayout.createSequentialGroup()
                        .addGroup(pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_background.add(pnl_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 1116, -1));

        pnl_details.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_details.setOpaque(false);
        pnl_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_detailsMouseClicked(evt);
            }
        });

        tbl_guardianDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Guardian ID", "First Name", "Last Name", "Type", "Mobile Number", "Home Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_guardianDetails.getTableHeader().setReorderingAllowed(false);
        tbl_guardianDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_guardianDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_guardianDetails);
        tbl_guardianDetails.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tbl_guardianDetails.getColumnModel().getColumnCount() > 0) {
            tbl_guardianDetails.getColumnModel().getColumn(0).setResizable(false);
            tbl_guardianDetails.getColumnModel().getColumn(1).setResizable(false);
            tbl_guardianDetails.getColumnModel().getColumn(2).setResizable(false);
            tbl_guardianDetails.getColumnModel().getColumn(3).setResizable(false);
            tbl_guardianDetails.getColumnModel().getColumn(4).setResizable(false);
            tbl_guardianDetails.getColumnModel().getColumn(5).setResizable(false);
        }

        btn_refresh.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_detailsLayout = new javax.swing.GroupLayout(pnl_details);
        pnl_details.setLayout(pnl_detailsLayout);
        pnl_detailsLayout.setHorizontalGroup(
            pnl_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .addGroup(pnl_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_detailsLayout.setVerticalGroup(
            pnl_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_refresh)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_background.add(pnl_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 136, 608, -1));

        lbl_background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_background.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1116, 501));

        getContentPane().add(pnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1116, 501));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        loadTblguardianreg();
        clearFields();
        tcl.setGuardianId(txt_id);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        saveToDb();
        loadTblguardianreg();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        updateRegistration();
        clearFields();
        tcl.setGuardianId(txt_id);
        loadTblguardianreg();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        searchingGuardian();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstNameKeyTyped
        tcl.grabFocus(txt_firstName, txt_lastName);
        tcl.LetersOnly.keyTyped(evt);
    }//GEN-LAST:event_txt_firstNameKeyTyped

    private void txt_lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastNameKeyTyped
        tcl.LetersAndSpaece.keyTyped(evt);
    }//GEN-LAST:event_txt_lastNameKeyTyped

    private void cmb_typeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_typeKeyTyped
        tcl.grabFocus(cmb_type, txt_mobileNumber);
    }//GEN-LAST:event_cmb_typeKeyTyped

    private void txt_mobileNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mobileNumberKeyTyped
        tcl.grabFocus(txt_mobileNumber, txt_homeNumber);
        tcl.NumbersOnly.keyTyped(evt);
        if (txt_mobileNumber.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_mobileNumberKeyTyped

    private void txt_homeNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_homeNumberKeyTyped
        tcl.grabFocus(txt_homeNumber, btn_save);
        tcl.NumbersOnly.keyTyped(evt);
        if (txt_homeNumber.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_homeNumberKeyTyped

    private void txt_homeNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_homeNumberFocusLost
        btn_save.setEnabled(true);
    }//GEN-LAST:event_txt_homeNumberFocusLost

    private void tbl_guardianDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_guardianDetailsMouseClicked
        tableMouseClicked();
    }//GEN-LAST:event_tbl_guardianDetailsMouseClicked

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        new Menu().setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void txt_lastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastNameKeyPressed
        if (evt.getKeyCode() == 38) {
            txt_firstName.grabFocus();
        }
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 40) {
            txt_mobileNumber.grabFocus();
        }
    }//GEN-LAST:event_txt_lastNameKeyPressed

    private void txt_mobileNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mobileNumberKeyPressed
        if (evt.getKeyCode() == 38) {
            txt_lastName.grabFocus();
        }
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 40) {
            txt_homeNumber.grabFocus();
        }
    }//GEN-LAST:event_txt_mobileNumberKeyPressed

    private void txt_firstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstNameKeyPressed
        if (evt.getKeyCode() == 38) {
            txt_search.grabFocus();
        }
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 40) {
            txt_lastName.grabFocus();
        }
    }//GEN-LAST:event_txt_firstNameKeyPressed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 40) {
            txt_firstName.grabFocus();
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tcl.setGuardianId(txt_id);
        clearFields();
        loadTblguardianreg();
        cmb_salutation.grabFocus();
    }//GEN-LAST:event_formWindowActivated

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
        txt_search.setText("");
    }//GEN-LAST:event_txt_searchFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        selectGuardian = "";
    }//GEN-LAST:event_formWindowClosing

    private void popup_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menuActionPerformed
         this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_popup_menuActionPerformed

    private void popup_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_exitActionPerformed
      this.dispose();
    }//GEN-LAST:event_popup_exitActionPerformed

    private void pnl_backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_backgroundMouseClicked
        if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_backgroundMouseClicked

    private void pnl_headerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_headerMouseClicked
       if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_headerMouseClicked

    private void pnl_guardianDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_guardianDetailsMouseClicked
       if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_guardianDetailsMouseClicked

    private void pnl_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_searchMouseClicked
        if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_searchMouseClicked

    private void pnl_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_detailsMouseClicked
        if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_detailsMouseClicked

    private void popup_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_helpActionPerformed
        try {
            Desktop.getDesktop().open(new File("E:\\Syndicate\\Documentation\\General – Student Registration.pdf"));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_popup_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuardianRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuardianRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuardianRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuardianRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuardianRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cmb_salutation;
    private javax.swing.JComboBox cmb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_homeNumber;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_mobileNumber;
    private javax.swing.JLabel lbl_salutation;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_details;
    private javax.swing.JPanel pnl_guardianDetails;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_search;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem popup_exit;
    private javax.swing.JMenuItem popup_help;
    private javax.swing.JMenuItem popup_menu;
    private javax.swing.JTable tbl_guardianDetails;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_homeNumber;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_mobileNumber;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

//--Loading guardian details table--//    
    private void loadTblguardianreg() {
        try {

            if (!(selectGuardian.equals(""))) {

                tcl.clearTable(tbl_guardianDetails);

                ResultSet rs = db.getData("SELECT * FROM guardion_details WHERE guardion_id= '" + selectGuardian + "'");

                while (rs.next()) {

                    String id = rs.getString("guardion_id");
                    String fname = rs.getString("f_name");
                    String lname = rs.getString("l_name");
                    String gtype = rs.getString("type");
                    String mobileno = rs.getString("mobile_no");
                    String homeno = rs.getString("home_no");

                    tcl.addToTable(tbl_guardianDetails, id, fname, lname, gtype, mobileno, homeno);
                }

            } else if (selectGuardian.equals("")) {

                tcl.clearTable(tbl_guardianDetails);

                ResultSet rs = db.getData("SELECT * FROM guardion_details");

                while (rs.next()) {
                    String id = rs.getString("guardion_id");
                    String fname = rs.getString("f_name");
                    String lname = rs.getString("l_name");
                    String gtype = rs.getString("type");
                    String mobileno = rs.getString("mobile_no");
                    String homeno = rs.getString("home_no");

                    tcl.addToTable(tbl_guardianDetails, id, fname, lname, gtype, mobileno, homeno);
                }
            }
            
        } catch (Exception ex) {
            System.out.println("Inside loadTblguardianreg() " + ex);
        }
    }
//--End of Loading guardian details table--//

//--Updating guardian details--//
    private void updateRegistration() {
        try {

            int salId = cmb_salutation.getSelectedIndex() + 1;

            db.putData("UPDATE guardion_details SET f_name = '" + txt_firstName.getText() + "',"
                    + " l_name = '" + txt_lastName.getText() + "', type = '" + cmb_type.getSelectedItem().toString() + "',"
                    + " mobile_no = '" + txt_mobileNumber.getText() + "', home_no = '" + txt_homeNumber.getText() + "',"
                    + " salutation_id = (SELECT salutation_id FROM salutation WHERE salutation_id = " + salId + ") WHERE guardion_id='" + txt_id.getText() + "'");

        } catch (Exception e) {
            System.out.println("Inside updateRegistration() " + e);
            e.printStackTrace();
        }
    }
//--End of Updating guardian details--//

//--Save a Guardian--//
    private void saveToDb() {
        try {

            if (txt_firstName.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Fields cannot Be Empty!");
                txt_firstName.grabFocus();

            } else if (txt_lastName.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Fields cannot Be Empty!");
                txt_lastName.grabFocus();

            } else if (txt_mobileNumber.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Fields cannot Be Empty!");
                txt_mobileNumber.grabFocus();

            } else if (txt_homeNumber.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Fields cannot Be Empty!");
                txt_homeNumber.grabFocus();

            } else {
                
                RegistrationFee.GRsalutation = "";
                if (cmb_salutation.getSelectedItem().equals("Mr")) {
                    RegistrationFee.GRsalutation = "1";
                } else if (cmb_salutation.getSelectedItem().equals("Mrs")) {
                    RegistrationFee.GRsalutation = "2";
                } else if (cmb_salutation.getSelectedItem().equals("Miss")) {
                    RegistrationFee.GRsalutation = "3";
                } else if (cmb_salutation.getSelectedItem().equals("Rev")) {
                    RegistrationFee.GRsalutation = "4";
                }
                RegistrationFee.GRfname = txt_firstName.getText().toString();
                RegistrationFee.GRlname = txt_lastName.getText().toString();

                switch (cmb_type.getSelectedItem().toString()) {
                    case "Parent":
                        RegistrationFee.GRtype = "Parent";
                        break;
                    case "Guardian":
                        RegistrationFee.GRtype = "Guardian";
                        break;
                }

                RegistrationFee.GRmobile = Integer.parseInt(txt_mobileNumber.getText());
                RegistrationFee.GRlandno = Integer.parseInt(txt_homeNumber.getText());

                RegistrationFee.GRguardianid = txt_id.getText().toString();

                //--Saving student_payment_invoice and income tables--//
                System.out.println("Guardian save ok");
                RegistrationFee.guardian = this;
                new RegistrationFee().setVisible(true);
                //--End of saving student_payment_invoice and income tables--//
            }
        } catch (Exception ex) {
            System.out.println("saveToDb in Guardian Registration " + ex);
            ex.printStackTrace();
        }
    }

//--Searching an guardian--//
    private void searchingGuardian() {
        try {
            String search = "%" + txt_search.getText() + "%";

            if (txt_search.getText().equals("")) {

                JOptionPane.showMessageDialog(rootPane, "Please Enter a Name to Search");
                loadTblguardianreg();
                txt_search.setText("");
                txt_search.grabFocus();

            } else {

                tcl.clearTable(tbl_guardianDetails);

                ResultSet rs = db.getData("SELECT * FROM guardion_details WHERE f_name LIKE '" + search + "' OR l_name LIKE '" + search + "'");

                while (rs.next()) {

                    String id = rs.getString("guardion_id");
                    String fname = rs.getString("f_name");
                    String lname = rs.getString("l_name");
                    String gtype = rs.getString("type");
                    String mobileno = rs.getString("mobile_no");
                    String homeno = rs.getString("home_no");
                    tcl.addToTable(tbl_guardianDetails, id, fname, lname, gtype, mobileno, homeno);
                }
            }
        } catch (Exception e) {
            System.out.println("Inside the searchingGuardian() " + e);
            e.printStackTrace();
        }
    }
//--End of searching an guardian--//

//--Start of MouseClick tableMouseClick() method--//
    private void tableMouseClicked() {
        clearFields();
        DefaultTableModel deftbl = (DefaultTableModel) tbl_guardianDetails.getModel();
        sr = tbl_guardianDetails.getSelectedRow();

        txt_id.setText((String) deftbl.getValueAt(sr, 0));
        txt_firstName.setText((String) deftbl.getValueAt(sr, 1));
        txt_lastName.setText((String) deftbl.getValueAt(sr, 2));
        txt_mobileNumber.setText((String) deftbl.getValueAt(sr, 4));
        txt_homeNumber.setText((String) deftbl.getValueAt(sr, 5));
    }
//--End of MouseClick--//

//--Clear fields--//
    private void clearFields() {
        txt_firstName.setText("");
        txt_lastName.setText("");
        txt_mobileNumber.setText("");
        txt_homeNumber.setText("");
        txt_search.setText("");
    }
//--Clear fields--//
}
