/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.JDBC;
import Uditha.AnimationClass;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Uditha N. Bandara
 */
public class Home extends javax.swing.JFrame {

    JDBC db = new JDBC();

    AnimationClass ac = new AnimationClass();
    int i = 0;
    Menu m;
    public static String un;
    public static String ut;

    public int adminPanel;
    public int adminStudentDetails;
    public int adminAttendanceDetails;
    public int adminEmployeeDetails;
    public int adminExpenses;
    public int adminTeacherDetails;
    public int adminSalaryInvoice;
    public int adminIncomeDetails;
    public int studentRegistration;
    public int expenses;
    public int expensesTeacherPayments;
    public int expensesSalary;
    public int expensesOtherPayments;
    public int employeeRegistration;
    public int teacherRegistration;
    public int userRegistration;
    public int classDetails;
    public int teacherTimetable;
    public int mainTimetable;
    public int attendance;
    public int leaves;
    public int studentPayments;
    public int jobTitle;
    public int subject;
    public int qualification;
    public int backupNRestore;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        lbl_username.setText(Login.Login.username);
        lbl_userType.setText(Login.Login.homeSetType);
        un = lbl_username.getText();
        ut = lbl_userType.getText();
        checkPrivilages();
        lbl_date.setText(new Classes.Commons().Date());
        new Classes.Commons().time(lbl_time);
    }

    public Home(JFrame f) {
        initComponents();
        this.m = (Menu) f;
        m.setVisible(true);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();
        lbl_userType = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_background02 = new javax.swing.JLabel();
        lbl_background01 = new javax.swing.JLabel();
        lbl_background00 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_backgroundMouseClicked(evt);
            }
        });
        pnl_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_header.setBackground(new java.awt.Color(255, 255, 255));
        pnl_header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_headerMouseClicked(evt);
            }
        });
        pnl_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        pnl_header.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 32, 32));

        lbl_userType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_userType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_userType.setText("User type");
        pnl_header.add(lbl_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 220, -1));

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_username.setText("Username");
        pnl_header.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 220, -1));

        lbl_date.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_date.setText("jLabel3");
        pnl_header.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        lbl_time.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_time.setText("jLabel3");
        pnl_header.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 23, 100, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Home");
        pnl_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 340, 30));

        pnl_background.add(pnl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 50));

        lbl_background02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img02.png"))); // NOI18N
        pnl_background.add(lbl_background02, new org.netbeans.lib.awtextra.AbsoluteConstraints(1366, 0, 1366, 768));

        lbl_background01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img01.png"))); // NOI18N
        pnl_background.add(lbl_background01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        lbl_background00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        lbl_background00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_background.add(lbl_background00, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        getContentPane().add(pnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Classes.Commons.FadeIn(this);
    }//GEN-LAST:event_formWindowOpened

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        new Menu(this).setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void pnl_headerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_headerMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_pnl_headerMouseClicked

    private void pnl_backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_backgroundMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_backgroundMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_background00;
    private javax.swing.JLabel lbl_background01;
    private javax.swing.JLabel lbl_background02;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_header;
    // End of variables declaration//GEN-END:variables
    //--Slideshow code start--
    void checkPrivilages() {
        try {
            ResultSet rs = db.getData("SELECT\n"
                    + "  job_title.*,\n"
                    + "  acces_privilages.*\n"
                    + "FROM\n"
                    + "  job_title\n"
                    + "INNER JOIN\n"
                    + "  acces_privilages\n"
                    + "ON (job_title.acces_privilages_id=acces_privilages.acces_privilages_id)\n"
                    + "WHERE job_name='"+lbl_userType.getText()+"'");

            while (rs.next()) {
                adminPanel = Integer.parseInt(rs.getString("adminPanel"));
                adminStudentDetails = Integer.parseInt(rs.getString("adminStudentDetails"));
                adminAttendanceDetails = Integer.parseInt(rs.getString("adminAttendanceDetails"));
                adminEmployeeDetails = Integer.parseInt(rs.getString("adminEmployeeDetails"));
                adminExpenses = Integer.parseInt(rs.getString("adminExpenses"));
                adminTeacherDetails = Integer.parseInt(rs.getString("adminTeacherDetails"));
                adminSalaryInvoice = Integer.parseInt(rs.getString("adminSalaryInvoice"));
                adminIncomeDetails = Integer.parseInt(rs.getString("adminIncomeDetails"));
                studentRegistration = Integer.parseInt(rs.getString("studentRegistration"));
                expenses = Integer.parseInt(rs.getString("expenses"));
                expensesTeacherPayments = Integer.parseInt(rs.getString("expensesTeacherPayments"));
                expensesSalary = Integer.parseInt(rs.getString("expensesSalary"));
                expensesOtherPayments = Integer.parseInt(rs.getString("expensesOtherPayments"));
                employeeRegistration = Integer.parseInt(rs.getString("employeeRegistration"));
                teacherRegistration = Integer.parseInt(rs.getString("teacherRegistration"));
                userRegistration = Integer.parseInt(rs.getString("userRegistration"));
                classDetails = Integer.parseInt(rs.getString("classDetails"));
                teacherTimetable = Integer.parseInt(rs.getString("teacherTimetable"));
                mainTimetable = Integer.parseInt(rs.getString("mainTimetable"));
                attendance = Integer.parseInt(rs.getString("attendance"));
                leaves = Integer.parseInt(rs.getString("leaves"));
                studentPayments = Integer.parseInt(rs.getString("studentPayments"));
                jobTitle = Integer.parseInt(rs.getString("jobTitle"));
                subject = Integer.parseInt(rs.getString("subject"));
                qualification = Integer.parseInt(rs.getString("qualification"));
                backupNRestore = Integer.parseInt(rs.getString("backup"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
