/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Admin.AdminStudentRegistration;
import Admin.Attendance;
import Admin.EmployeeDetails;
import Admin.Expences;
import Admin.IncomeDetails;
import Admin.SalaryInvoice;
import Admin.TeacherDetails;
import Uditha.AnimationClass;
import java.awt.Desktop;
import java.awt.Window;
import java.io.File;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Uditha N. Bandara
 */
public class Menu extends javax.swing.JFrame {

    AnimationClass ac = new AnimationClass();
    int i = 0;
    int k = 0;

    public static String un;
    public static String ut;

    private final int adminPanel = new GUI.Home().adminPanel;
    private final int adminStudentDetails = new GUI.Home().adminStudentDetails;
    private final int adminAttendanceDetails = new GUI.Home().adminAttendanceDetails;
    private final int adminEmployeeDetails = new GUI.Home().adminEmployeeDetails;
    private final int adminExpenses = new GUI.Home().adminExpenses;
    private final int adminTeacherDetails = new GUI.Home().adminTeacherDetails;
    private final int adminSalaryInvoice = new GUI.Home().adminSalaryInvoice;
    private final int adminIncomeDetails = new GUI.Home().adminIncomeDetails;
    private final int studentRegistration = new GUI.Home().studentRegistration;
    private final int expenses = new GUI.Home().expenses;
    private final int expensesTeacherPayments = new GUI.Home().expensesTeacherPayments;
    private final int expensesSalary = new GUI.Home().expensesSalary;
    private final int expensesOtherPayments = new GUI.Home().expensesOtherPayments;
    private final int employeeRegistration = new GUI.Home().employeeRegistration;
    private final int teacherRegistration = new GUI.Home().teacherRegistration;
    private final int userRegistration = new GUI.Home().userRegistration;
    private final int classDetails = new GUI.Home().classDetails;
    private final int teacherTimetable = new GUI.Home().teacherTimetable;
    private final int mainTimetable = new GUI.Home().mainTimetable;
    private final int attendance = new GUI.Home().attendance;
    private final int leaves = new GUI.Home().leaves;
    private final int studentPayments = new GUI.Home().studentPayments;
    private final int jobTitle = new GUI.Home().jobTitle;
    private final int subject = new GUI.Home().subject;
    private final int qualification = new GUI.Home().qualification;
    private final int backupNRestore = new GUI.Home().backupNRestore;

    /**
     * Creates new form Menu
     */
    Home home;

    public Menu() {
        System.out.println("1");
        initComponents();
        System.out.println("2");
        com.sun.awt.AWTUtilities.setWindowOpaque(this, false);
        System.out.println("3");
        lbl_username.setText(GUI.Home.un);
        System.out.println("4");
        lbl_userType.setText(GUI.Home.ut);
        System.out.println("5");
        restrictButtons();
        System.out.println("6");
//        un = lbl_username.getText();
//        ut = lbl_userType.getText();
    }

    public Menu(Home home1) {
        System.out.println("1");
        initComponents();
        System.out.println("2");
        com.sun.awt.AWTUtilities.setWindowOpaque(this, false);
        System.out.println("3");
        lbl_username.setText(GUI.Home.un);
        System.out.println("4");
        lbl_userType.setText(GUI.Home.ut);
        System.out.println("5");
        restrictButtons();
        System.out.println("6");
//        un = lbl_username.getText();
//        ut = lbl_userType.getText();
        home = home1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();
        pnl_expenses = new javax.swing.JPanel();
        btn_exTeacherPayments = new javax.swing.JButton();
        btn_exOtherPayments = new javax.swing.JButton();
        btn_exSalary = new javax.swing.JButton();
        pnl_adminPanel = new javax.swing.JPanel();
        btn_adStudentDetails = new javax.swing.JButton();
        btn_adEmployeeDetails = new javax.swing.JButton();
        btn_adAttendanceDetails = new javax.swing.JButton();
        btn_adExpenses = new javax.swing.JButton();
        btn_adTeacherDetails = new javax.swing.JButton();
        btn_adSalaryInvoice = new javax.swing.JButton();
        btn_adIncomeDetails = new javax.swing.JButton();
        btn_companyDetails = new javax.swing.JButton();
        pnl_buttonBackground = new javax.swing.JPanel();
        btn_01studentRegistration = new javax.swing.JButton();
        btn_02employeeRegistration = new javax.swing.JButton();
        btn_03teacherRegistration = new javax.swing.JButton();
        btn_04userRegistration = new javax.swing.JButton();
        btn_05classDetails = new javax.swing.JButton();
        btn_06teacherTimetable = new javax.swing.JButton();
        btn_07mainTimetable = new javax.swing.JButton();
        btn_08resetPassword = new javax.swing.JButton();
        btn_09attendance = new javax.swing.JButton();
        btn_10leaves = new javax.swing.JButton();
        btn_11expenses = new javax.swing.JButton();
        btn_12studentPayments = new javax.swing.JButton();
        btn_13jobTitle = new javax.swing.JButton();
        btn_14subject = new javax.swing.JButton();
        btn_15qualification = new javax.swing.JButton();
        btn_16backupNRestore = new javax.swing.JButton();
        pnl_panelBack = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        lbl_userType = new javax.swing.JLabel();
        btn_lockScreen = new javax.swing.JButton();
        btn_adminPanel = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_about = new javax.swing.JButton();
        btn_help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_background.setBackground(Classes.Commons.Transparent);
        pnl_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu2.png"))); // NOI18N
        btn_menu.setContentAreaFilled(false);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        pnl_background.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 32, 32));

        pnl_expenses.setBackground(new java.awt.Color(51, 51, 51));

        btn_exTeacherPayments.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_exTeacherPayments.setForeground(new java.awt.Color(255, 255, 255));
        btn_exTeacherPayments.setText("Teacher Payments");
        btn_exTeacherPayments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_exTeacherPayments.setContentAreaFilled(false);
        btn_exTeacherPayments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exTeacherPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exTeacherPaymentsActionPerformed(evt);
            }
        });

        btn_exOtherPayments.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_exOtherPayments.setForeground(new java.awt.Color(255, 255, 255));
        btn_exOtherPayments.setText("Other Payments");
        btn_exOtherPayments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_exOtherPayments.setContentAreaFilled(false);
        btn_exOtherPayments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exOtherPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exOtherPaymentsActionPerformed(evt);
            }
        });

        btn_exSalary.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_exSalary.setForeground(new java.awt.Color(255, 255, 255));
        btn_exSalary.setText("Salary");
        btn_exSalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_exSalary.setContentAreaFilled(false);
        btn_exSalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exSalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_expensesLayout = new javax.swing.GroupLayout(pnl_expenses);
        pnl_expenses.setLayout(pnl_expensesLayout);
        pnl_expensesLayout.setHorizontalGroup(
            pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_expensesLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btn_exTeacherPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exOtherPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(632, Short.MAX_VALUE))
        );
        pnl_expensesLayout.setVerticalGroup(
            pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_expensesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exTeacherPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exOtherPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnl_background.add(pnl_expenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 768, 1366, 60));

        pnl_adminPanel.setBackground(new java.awt.Color(51, 51, 51));

        btn_adStudentDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adStudentDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_adStudentDetails.setText("Student Details");
        btn_adStudentDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adStudentDetails.setContentAreaFilled(false);
        btn_adStudentDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adStudentDetailsActionPerformed(evt);
            }
        });

        btn_adEmployeeDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adEmployeeDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_adEmployeeDetails.setText("Employee Details");
        btn_adEmployeeDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adEmployeeDetails.setContentAreaFilled(false);
        btn_adEmployeeDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adEmployeeDetailsActionPerformed(evt);
            }
        });

        btn_adAttendanceDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adAttendanceDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_adAttendanceDetails.setText("Attendance Details");
        btn_adAttendanceDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adAttendanceDetails.setContentAreaFilled(false);
        btn_adAttendanceDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adAttendanceDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adAttendanceDetailsActionPerformed(evt);
            }
        });

        btn_adExpenses.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adExpenses.setForeground(new java.awt.Color(255, 255, 255));
        btn_adExpenses.setText("Expenses");
        btn_adExpenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adExpenses.setContentAreaFilled(false);
        btn_adExpenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adExpensesActionPerformed(evt);
            }
        });

        btn_adTeacherDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adTeacherDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_adTeacherDetails.setText("Teacher Details");
        btn_adTeacherDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adTeacherDetails.setContentAreaFilled(false);
        btn_adTeacherDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adTeacherDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adTeacherDetailsActionPerformed(evt);
            }
        });

        btn_adSalaryInvoice.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adSalaryInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btn_adSalaryInvoice.setText("Salary Invoice");
        btn_adSalaryInvoice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adSalaryInvoice.setContentAreaFilled(false);
        btn_adSalaryInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adSalaryInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adSalaryInvoiceActionPerformed(evt);
            }
        });

        btn_adIncomeDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adIncomeDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_adIncomeDetails.setText("Income Details");
        btn_adIncomeDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adIncomeDetails.setContentAreaFilled(false);
        btn_adIncomeDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adIncomeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adIncomeDetailsActionPerformed(evt);
            }
        });

        btn_companyDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_companyDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_companyDetails.setText("Company Details");
        btn_companyDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_companyDetails.setContentAreaFilled(false);
        btn_companyDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_companyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_companyDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_adminPanelLayout = new javax.swing.GroupLayout(pnl_adminPanel);
        pnl_adminPanel.setLayout(pnl_adminPanelLayout);
        pnl_adminPanelLayout.setHorizontalGroup(
            pnl_adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_adStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adAttendanceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adSalaryInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adIncomeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_companyDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnl_adminPanelLayout.setVerticalGroup(
            pnl_adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adAttendanceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adTeacherDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adSalaryInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adIncomeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_companyDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_background.add(pnl_adminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 768, 1366, 60));

        pnl_buttonBackground.setOpaque(false);
        pnl_buttonBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_01studentRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img01.png"))); // NOI18N
        btn_01studentRegistration.setContentAreaFilled(false);
        btn_01studentRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_01studentRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_01studentRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_01studentRegistrationMouseExited(evt);
            }
        });
        btn_01studentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_01studentRegistrationActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_01studentRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 284, 120));

        btn_02employeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img02.png"))); // NOI18N
        btn_02employeeRegistration.setContentAreaFilled(false);
        btn_02employeeRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_02employeeRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_02employeeRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_02employeeRegistrationMouseExited(evt);
            }
        });
        btn_02employeeRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02employeeRegistrationActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_02employeeRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 0, 284, 120));

        btn_03teacherRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img03.png"))); // NOI18N
        btn_03teacherRegistration.setContentAreaFilled(false);
        btn_03teacherRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_03teacherRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_03teacherRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_03teacherRegistrationMouseExited(evt);
            }
        });
        btn_03teacherRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03teacherRegistrationActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_03teacherRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 0, 284, 120));

        btn_04userRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img04.png"))); // NOI18N
        btn_04userRegistration.setContentAreaFilled(false);
        btn_04userRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_04userRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_04userRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_04userRegistrationMouseExited(evt);
            }
        });
        btn_04userRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04userRegistrationActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_04userRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 0, 284, 120));

        btn_05classDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img05.png"))); // NOI18N
        btn_05classDetails.setContentAreaFilled(false);
        btn_05classDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_05classDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_05classDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_05classDetailsMouseExited(evt);
            }
        });
        btn_05classDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05classDetailsActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_05classDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 284, 120));

        btn_06teacherTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img06.png"))); // NOI18N
        btn_06teacherTimetable.setContentAreaFilled(false);
        btn_06teacherTimetable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_06teacherTimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_06teacherTimetableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_06teacherTimetableMouseExited(evt);
            }
        });
        btn_06teacherTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06teacherTimetableActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_06teacherTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 130, 284, 120));

        btn_07mainTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img07.png"))); // NOI18N
        btn_07mainTimetable.setContentAreaFilled(false);
        btn_07mainTimetable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_07mainTimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_07mainTimetableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_07mainTimetableMouseExited(evt);
            }
        });
        btn_07mainTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_07mainTimetableActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_07mainTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 130, 284, 120));

        btn_08resetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img08.png"))); // NOI18N
        btn_08resetPassword.setContentAreaFilled(false);
        btn_08resetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_08resetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_08resetPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_08resetPasswordMouseExited(evt);
            }
        });
        btn_08resetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_08resetPasswordActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_08resetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 130, 284, 120));

        btn_09attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img09.png"))); // NOI18N
        btn_09attendance.setContentAreaFilled(false);
        btn_09attendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_09attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_09attendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_09attendanceMouseExited(evt);
            }
        });
        btn_09attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09attendanceActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_09attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 284, 120));

        btn_10leaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img10.png"))); // NOI18N
        btn_10leaves.setContentAreaFilled(false);
        btn_10leaves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_10leaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_10leavesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_10leavesMouseExited(evt);
            }
        });
        btn_10leaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_10leavesActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_10leaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 260, 284, 120));

        btn_11expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img11.png"))); // NOI18N
        btn_11expenses.setContentAreaFilled(false);
        btn_11expenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_11expenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_11expensesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_11expensesMouseExited(evt);
            }
        });
        btn_11expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_11expensesActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_11expenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 260, 284, 120));

        btn_12studentPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img12.png"))); // NOI18N
        btn_12studentPayments.setContentAreaFilled(false);
        btn_12studentPayments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_12studentPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_12studentPaymentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_12studentPaymentsMouseExited(evt);
            }
        });
        btn_12studentPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_12studentPaymentsActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_12studentPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 260, 284, 120));

        btn_13jobTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img13.png"))); // NOI18N
        btn_13jobTitle.setContentAreaFilled(false);
        btn_13jobTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_13jobTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_13jobTitleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_13jobTitleMouseExited(evt);
            }
        });
        btn_13jobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_13jobTitleActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_13jobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 284, 120));

        btn_14subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img14.png"))); // NOI18N
        btn_14subject.setContentAreaFilled(false);
        btn_14subject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_14subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_14subjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_14subjectMouseExited(evt);
            }
        });
        btn_14subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_14subjectActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_14subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 390, 284, 120));

        btn_15qualification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img15.png"))); // NOI18N
        btn_15qualification.setContentAreaFilled(false);
        btn_15qualification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_15qualification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_15qualificationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_15qualificationMouseExited(evt);
            }
        });
        btn_15qualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_15qualificationActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_15qualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 390, 284, 120));

        btn_16backupNRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img16.png"))); // NOI18N
        btn_16backupNRestore.setContentAreaFilled(false);
        btn_16backupNRestore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_16backupNRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_16backupNRestoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_16backupNRestoreMouseExited(evt);
            }
        });
        btn_16backupNRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_16backupNRestoreActionPerformed(evt);
            }
        });
        pnl_buttonBackground.add(btn_16backupNRestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 390, 284, 120));

        pnl_background.add(pnl_buttonBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 1166, 510));

        pnl_panelBack.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnl_panelBackLayout = new javax.swing.GroupLayout(pnl_panelBack);
        pnl_panelBack.setLayout(pnl_panelBackLayout);
        pnl_panelBackLayout.setHorizontalGroup(
            pnl_panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnl_panelBackLayout.setVerticalGroup(
            pnl_panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnl_background.add(pnl_panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 708, 1366, 60));

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_username.setText("Username");
        pnl_background.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 220, -1));

        lbl_userType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_userType.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_userType.setText("User Type");
        pnl_background.add(lbl_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 220, -1));

        btn_lockScreen.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_lockScreen.setForeground(new java.awt.Color(255, 255, 255));
        btn_lockScreen.setText("Lock Screen");
        btn_lockScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_lockScreen.setContentAreaFilled(false);
        btn_lockScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lockScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lockScreenActionPerformed(evt);
            }
        });
        pnl_background.add(btn_lockScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 188, 44));

        btn_adminPanel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_adminPanel.setForeground(new java.awt.Color(255, 255, 255));
        btn_adminPanel.setText("Admin Panel");
        btn_adminPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_adminPanel.setContentAreaFilled(false);
        btn_adminPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminPanelActionPerformed(evt);
            }
        });
        pnl_background.add(btn_adminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 630, 188, 44));

        btn_logout.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_logout.setContentAreaFilled(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        pnl_background.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 188, 44));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        pnl_background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 340, 30));

        btn_about.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_about.setForeground(new java.awt.Color(255, 255, 255));
        btn_about.setText("About Us");
        btn_about.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_about.setContentAreaFilled(false);
        btn_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });
        pnl_background.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 188, 44));

        btn_help.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_help.setForeground(new java.awt.Color(255, 255, 255));
        btn_help.setText("Help");
        btn_help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_help.setContentAreaFilled(false);
        btn_help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_helpActionPerformed(evt);
            }
        });
        pnl_background.add(btn_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, 188, 44));

        getContentPane().add(pnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Classes.Commons.FadeIn(this);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_01studentRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_01studentRegistrationMouseEntered
        btn_01studentRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img01 hover.png")));
    }//GEN-LAST:event_btn_01studentRegistrationMouseEntered

    private void btn_01studentRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_01studentRegistrationMouseExited
        btn_01studentRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img01.png")));
    }//GEN-LAST:event_btn_01studentRegistrationMouseExited

    private void btn_02employeeRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_02employeeRegistrationMouseEntered
        btn_02employeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img02 hover.png")));
    }//GEN-LAST:event_btn_02employeeRegistrationMouseEntered

    private void btn_03teacherRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_03teacherRegistrationMouseEntered
        btn_03teacherRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img03 hover.png")));
    }//GEN-LAST:event_btn_03teacherRegistrationMouseEntered

    private void btn_04userRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_04userRegistrationMouseEntered
        btn_04userRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img04 hover.png")));
    }//GEN-LAST:event_btn_04userRegistrationMouseEntered

    private void btn_05classDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_05classDetailsMouseEntered
        btn_05classDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img05 hover.png")));
    }//GEN-LAST:event_btn_05classDetailsMouseEntered

    private void btn_06teacherTimetableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_06teacherTimetableMouseEntered
        btn_06teacherTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img06 hover.png")));
    }//GEN-LAST:event_btn_06teacherTimetableMouseEntered

    private void btn_07mainTimetableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_07mainTimetableMouseEntered
        btn_07mainTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img07 hover.png")));
    }//GEN-LAST:event_btn_07mainTimetableMouseEntered

    private void btn_08resetPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_08resetPasswordMouseEntered
        btn_08resetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img08 hover.png")));
    }//GEN-LAST:event_btn_08resetPasswordMouseEntered

    private void btn_09attendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_09attendanceMouseEntered
        btn_09attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img09 hover.png")));
    }//GEN-LAST:event_btn_09attendanceMouseEntered

    private void btn_10leavesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10leavesMouseEntered
        btn_10leaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img10 hover.png")));
    }//GEN-LAST:event_btn_10leavesMouseEntered

    private void btn_11expensesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11expensesMouseEntered
        btn_11expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img11 hover.png")));
    }//GEN-LAST:event_btn_11expensesMouseEntered

    private void btn_12studentPaymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12studentPaymentsMouseEntered
        btn_12studentPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img12 hover.png")));
    }//GEN-LAST:event_btn_12studentPaymentsMouseEntered

    private void btn_13jobTitleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_13jobTitleMouseEntered
        btn_13jobTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img13 hover.png")));
    }//GEN-LAST:event_btn_13jobTitleMouseEntered

    private void btn_14subjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_14subjectMouseEntered
        btn_14subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img14 hover.png")));
    }//GEN-LAST:event_btn_14subjectMouseEntered

    private void btn_15qualificationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_15qualificationMouseEntered
        btn_15qualification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img15 hover.png")));
    }//GEN-LAST:event_btn_15qualificationMouseEntered

    private void btn_02employeeRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_02employeeRegistrationMouseExited
        btn_02employeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img02.png")));
    }//GEN-LAST:event_btn_02employeeRegistrationMouseExited

    private void btn_03teacherRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_03teacherRegistrationMouseExited
        btn_03teacherRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img03.png")));
    }//GEN-LAST:event_btn_03teacherRegistrationMouseExited

    private void btn_04userRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_04userRegistrationMouseExited
        btn_04userRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img04.png")));
    }//GEN-LAST:event_btn_04userRegistrationMouseExited

    private void btn_05classDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_05classDetailsMouseExited
        btn_05classDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img05.png")));
    }//GEN-LAST:event_btn_05classDetailsMouseExited

    private void btn_06teacherTimetableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_06teacherTimetableMouseExited
        btn_06teacherTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img06.png")));
    }//GEN-LAST:event_btn_06teacherTimetableMouseExited

    private void btn_07mainTimetableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_07mainTimetableMouseExited
        btn_07mainTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img07.png")));
    }//GEN-LAST:event_btn_07mainTimetableMouseExited

    private void btn_08resetPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_08resetPasswordMouseExited
        btn_08resetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img08.png")));
    }//GEN-LAST:event_btn_08resetPasswordMouseExited

    private void btn_09attendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_09attendanceMouseExited
        btn_09attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img09.png")));
    }//GEN-LAST:event_btn_09attendanceMouseExited

    private void btn_10leavesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10leavesMouseExited
        btn_10leaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img10.png")));
    }//GEN-LAST:event_btn_10leavesMouseExited

    private void btn_11expensesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_11expensesMouseExited
        btn_11expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img11.png")));
    }//GEN-LAST:event_btn_11expensesMouseExited

    private void btn_12studentPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_12studentPaymentsActionPerformed
        Classes.Commons.FadeOut(this);
        this.dispose();
        new studentPayment().setVisible(true);
    }//GEN-LAST:event_btn_12studentPaymentsActionPerformed

    private void btn_12studentPaymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_12studentPaymentsMouseExited
        btn_12studentPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img12.png")));
    }//GEN-LAST:event_btn_12studentPaymentsMouseExited

    private void btn_13jobTitleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_13jobTitleMouseExited
        btn_13jobTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img13.png")));
    }//GEN-LAST:event_btn_13jobTitleMouseExited

    private void btn_14subjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_14subjectMouseExited
        btn_14subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img14.png")));
    }//GEN-LAST:event_btn_14subjectMouseExited

    private void btn_15qualificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_15qualificationMouseExited
        btn_15qualification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img15.png")));
    }//GEN-LAST:event_btn_15qualificationMouseExited

    private void btn_04userRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04userRegistrationActionPerformed
        Classes.Commons.FadeOut(this);
        this.dispose();
        new UserRegistration().setVisible(true);
    }//GEN-LAST:event_btn_04userRegistrationActionPerformed

    private void btn_11expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_11expensesActionPerformed
        i++;
        int j = i % 2;
        int getY = pnl_adminPanel.getY();
        if (getY == 708) {
            k++;
            if (j == 1) {
                ac.jPanelYUp(768, 708, 1, 1, pnl_expenses);
                ac.jPanelYDown(708, 768, 1, 1, pnl_adminPanel);
            } else if (j == 0) {
                ac.jPanelYDown(708, 768, 1, 1, pnl_expenses);
            }
        } else {
            if (j == 1) {
                ac.jPanelYUp(768, 708, 1, 1, pnl_expenses);
            } else if (j == 0) {
                ac.jPanelYDown(708, 768, 1, 1, pnl_expenses);
            }
        }
    }//GEN-LAST:event_btn_11expensesActionPerformed

    private void btn_adminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminPanelActionPerformed
        k++;
        int j = k % 2;
        int getY = pnl_expenses.getY();
        if (getY == 708) {
            i++;
            if (j == 1) {
                ac.jPanelYUp(768, 708, 1, 1, pnl_adminPanel);
                ac.jPanelYDown(708, 768, 1, 1, pnl_expenses);
            } else if (j == 0) {
                ac.jPanelYDown(708, 768, 1, 1, pnl_adminPanel);
            }
        } else {
            if (j == 1) {
                ac.jPanelYUp(768, 708, 1, 1, pnl_adminPanel);
            } else if (j == 0) {
                ac.jPanelYDown(708, 768, 1, 1, pnl_adminPanel);
            }
        }
    }//GEN-LAST:event_btn_adminPanelActionPerformed

    private void btn_08resetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_08resetPasswordActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Please saved all unsaved processes before reset the password.\nOtherwise all unsaved data will be lost.\nDid you save all the data?");
        if (i == 0) {
            Classes.Commons.FadeOut(this);
            this.dispose();
            new ResetPassword().setVisible(true);
        }
    }//GEN-LAST:event_btn_08resetPasswordActionPerformed

    private void btn_lockScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lockScreenActionPerformed
        Classes.Commons.FadeOut(this);
        this.dispose();
        Window[] jf = JFrame.getOwnerlessWindows();
        for (int i = 0; i < jf.length; i++) {
            JFrame f = (JFrame) jf[i];
            Classes.Commons.FadeOut(f);
        }
        new LockScreen().setVisible(true);
    }//GEN-LAST:event_btn_lockScreenActionPerformed

    private void btn_10leavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_10leavesActionPerformed
        // TODO add your handling code here:
        new Leaves().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_10leavesActionPerformed

    private void btn_adSalaryInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adSalaryInvoiceActionPerformed
        new SalaryInvoice().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_adSalaryInvoiceActionPerformed

    private void btn_adStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adStudentDetailsActionPerformed
        new AdminStudentRegistration().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_adStudentDetailsActionPerformed

    private void btn_adEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adEmployeeDetailsActionPerformed
        new EmployeeDetails().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_adEmployeeDetailsActionPerformed

    private void btn_adAttendanceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adAttendanceDetailsActionPerformed
        new Attendance().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_adAttendanceDetailsActionPerformed

    private void btn_adExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adExpensesActionPerformed
        new Expences().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_adExpensesActionPerformed

    private void btn_adTeacherDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adTeacherDetailsActionPerformed
        new TeacherDetails().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_adTeacherDetailsActionPerformed

    private void btn_01studentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_01studentRegistrationActionPerformed
        new StudentRegistration().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_01studentRegistrationActionPerformed

    private void btn_02employeeRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02employeeRegistrationActionPerformed
        new EmployeeRegistration().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_02employeeRegistrationActionPerformed

    private void btn_03teacherRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03teacherRegistrationActionPerformed
        new TeacherRegistration().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_03teacherRegistrationActionPerformed

    private void btn_05classDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05classDetailsActionPerformed
        new ClassDetails().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_05classDetailsActionPerformed

    private void btn_06teacherTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06teacherTimetableActionPerformed
        new TeacherTimetable().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_06teacherTimetableActionPerformed

    private void btn_07mainTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_07mainTimetableActionPerformed
        new MainTimeTable().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_07mainTimetableActionPerformed

    private void btn_09attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09attendanceActionPerformed
        new EmployeeAttendence().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_09attendanceActionPerformed

    private void btn_14subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_14subjectActionPerformed
        new AddSubject().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_14subjectActionPerformed

    private void btn_15qualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_15qualificationActionPerformed
        new AddQualification().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_15qualificationActionPerformed

    private void btn_13jobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_13jobTitleActionPerformed
        new AddJobTitle().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_13jobTitleActionPerformed

    private void btn_exTeacherPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exTeacherPaymentsActionPerformed
        new TeacherPayment().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_exTeacherPaymentsActionPerformed

    private void btn_exOtherPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exOtherPaymentsActionPerformed
        new Expenses().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_exOtherPaymentsActionPerformed

    private void btn_exSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exSalaryActionPerformed
        new Salary().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_exSalaryActionPerformed

    private void btn_16backupNRestoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_16backupNRestoreMouseEntered
        btn_16backupNRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img16 hover.png")));
    }//GEN-LAST:event_btn_16backupNRestoreMouseEntered

    private void btn_16backupNRestoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_16backupNRestoreMouseExited
        btn_16backupNRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu/img16.png")));
    }//GEN-LAST:event_btn_16backupNRestoreMouseExited

    private void btn_16backupNRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_16backupNRestoreActionPerformed
        new BackupNRestore().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_16backupNRestoreActionPerformed

    private void btn_adIncomeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adIncomeDetailsActionPerformed
        new IncomeDetails().setVisible(true);
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_btn_adIncomeDetailsActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Please saved all unsaved processes before logout.\nOtherwise all unsaved data will be lost.\nDid you save all the data?");
        if (i == 0) {
            Classes.Commons.FadeOut(this);
            Logger log = Logger.getLogger("Details");
            log.info("Log Out in :" + new SimpleDateFormat("HH:mm:ss").format(new Date()));
            
            Window[] jf = JFrame.getOwnerlessWindows();
            for (int j = 0; j < jf.length; j++) {
                JFrame f = (JFrame) jf[j];
                f.dispose();
            }
            
            new Login.Login().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed
        Classes.Commons.FadeOut(this);
        this.dispose();
        new About().setVisible(true);
    }//GEN-LAST:event_btn_aboutActionPerformed

    private void btn_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_helpActionPerformed
        try {
//          File f=new File(this.getClass().getClassLoader().getResource("//Help_File//Help File.pdf").getFile());
//          Desktop.getDesktop().open(f);
//            InputStream im=this.getClass().getClassLoader().getResourceAsStream("//Help_File//Help File.pdf");
//            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler //Help_File//Help File.pdf");
//           File f1= new File(new File("/Help_File/Help File.pdf").getAbsolutePath());
//            Desktop.getDesktop().print(f1);
            Desktop.getDesktop().open(new File("E:\\EDUCATION\\####FINAL VIVA\\Final Project\\Syndicate\\src\\Help_File\\Help File.pdf"));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_helpActionPerformed

    private void btn_companyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_companyDetailsActionPerformed
        Classes.Commons.FadeOut(this);
        this.dispose();
        new Admin.CompanyProfile().setVisible(true);
    }//GEN-LAST:event_btn_companyDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_01studentRegistration;
    private javax.swing.JButton btn_02employeeRegistration;
    private javax.swing.JButton btn_03teacherRegistration;
    private javax.swing.JButton btn_04userRegistration;
    private javax.swing.JButton btn_05classDetails;
    private javax.swing.JButton btn_06teacherTimetable;
    private javax.swing.JButton btn_07mainTimetable;
    private javax.swing.JButton btn_08resetPassword;
    private javax.swing.JButton btn_09attendance;
    private javax.swing.JButton btn_10leaves;
    private javax.swing.JButton btn_11expenses;
    private javax.swing.JButton btn_12studentPayments;
    private javax.swing.JButton btn_13jobTitle;
    private javax.swing.JButton btn_14subject;
    private javax.swing.JButton btn_15qualification;
    private javax.swing.JButton btn_16backupNRestore;
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_adAttendanceDetails;
    private javax.swing.JButton btn_adEmployeeDetails;
    private javax.swing.JButton btn_adExpenses;
    private javax.swing.JButton btn_adIncomeDetails;
    private javax.swing.JButton btn_adSalaryInvoice;
    private javax.swing.JButton btn_adStudentDetails;
    private javax.swing.JButton btn_adTeacherDetails;
    private javax.swing.JButton btn_adminPanel;
    private javax.swing.JButton btn_companyDetails;
    private javax.swing.JButton btn_exOtherPayments;
    private javax.swing.JButton btn_exSalary;
    private javax.swing.JButton btn_exTeacherPayments;
    private javax.swing.JButton btn_help;
    private javax.swing.JButton btn_lockScreen;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_adminPanel;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_buttonBackground;
    private javax.swing.JPanel pnl_expenses;
    private javax.swing.JPanel pnl_panelBack;
    // End of variables declaration//GEN-END:variables
    private void serHoverImage(JButton b, String s) {
        b.setIcon(new javax.swing.ImageIcon(getClass().getResource(s)));
    }

    void restrictButtons() {
        String userType = lbl_userType.getText();

        if (userType.equals("Admin")) {
            System.out.println("Admin");
        } else if (userType.equals("Teacher")) {
            disableButtons(btn_01studentRegistration, btn_02employeeRegistration, btn_08resetPassword);
        } else {
            if (adminPanel == 1) {
                btn_adminPanel.setEnabled(true);
            } else {
                btn_adminPanel.setEnabled(false);
            }

            if (adminStudentDetails == 1) {
                btn_adStudentDetails.setEnabled(true);
            } else {
                btn_adStudentDetails.setEnabled(false);
            }

            if (adminAttendanceDetails == 1) {
                btn_adAttendanceDetails.setEnabled(true);
            } else {
                btn_adAttendanceDetails.setEnabled(false);
            }

            if (adminEmployeeDetails == 1) {
                btn_adEmployeeDetails.setEnabled(true);
            } else {
                btn_adEmployeeDetails.setEnabled(false);
            }

            if (adminExpenses == 1) {
                btn_adExpenses.setEnabled(true);
            } else {
                btn_adExpenses.setEnabled(false);
            }

            if (adminTeacherDetails == 1) {
                btn_adTeacherDetails.setEnabled(true);
            } else {
                btn_adTeacherDetails.setEnabled(false);
            }

            if (adminSalaryInvoice == 1) {
                btn_adSalaryInvoice.setEnabled(true);
            } else {
                btn_adSalaryInvoice.setEnabled(false);
            }

            if (adminIncomeDetails == 1) {
                btn_adIncomeDetails.setEnabled(true);
            } else {
                btn_adIncomeDetails.setEnabled(false);
            }

            if (studentRegistration == 1) {
                btn_01studentRegistration.setEnabled(true);
            } else {
                btn_01studentRegistration.setEnabled(false);
            }

            if (expenses == 1) {
                btn_11expenses.setEnabled(true);
            } else {
                btn_11expenses.setEnabled(false);
            }

            if (expensesTeacherPayments == 1) {
                btn_exTeacherPayments.setEnabled(true);
            } else {
                btn_exTeacherPayments.setEnabled(false);
            }

            if (expensesSalary == 1) {
                btn_exSalary.setEnabled(true);
            } else {
                btn_exSalary.setEnabled(false);
            }

            if (expensesOtherPayments == 1) {
                btn_exOtherPayments.setEnabled(true);
            } else {
                btn_exOtherPayments.setEnabled(false);
            }

            if (employeeRegistration == 1) {
                btn_02employeeRegistration.setEnabled(true);
            } else {
                btn_02employeeRegistration.setEnabled(false);
            }

            if (teacherRegistration == 1) {
                btn_03teacherRegistration.setEnabled(true);
            } else {
                btn_03teacherRegistration.setEnabled(false);
            }

            if (userRegistration == 1) {
                btn_04userRegistration.setEnabled(true);
            } else {
                btn_04userRegistration.setEnabled(false);
            }

            if (classDetails == 1) {
                btn_05classDetails.setEnabled(true);
            } else {
                btn_05classDetails.setEnabled(false);
            }

            if (teacherTimetable == 1) {
                btn_06teacherTimetable.setEnabled(true);
            } else {
                btn_06teacherTimetable.setEnabled(false);
            }

            if (mainTimetable == 1) {
                btn_07mainTimetable.setEnabled(true);
            } else {
                btn_07mainTimetable.setEnabled(false);
            }

            if (attendance == 1) {
                btn_09attendance.setEnabled(true);
            } else {
                btn_09attendance.setEnabled(false);
            }

            if (leaves == 1) {
                btn_10leaves.setEnabled(true);
            } else {
                btn_10leaves.setEnabled(false);
            }

            if (studentPayments == 1) {
                btn_12studentPayments.setEnabled(true);
            } else {
                btn_12studentPayments.setEnabled(false);
            }

            if (jobTitle == 1) {
                btn_13jobTitle.setEnabled(true);
            } else {
                btn_13jobTitle.setEnabled(false);
            }

            if (subject == 1) {
                btn_14subject.setEnabled(true);
            } else {
                btn_14subject.setEnabled(false);
            }

            if (qualification == 1) {
                btn_15qualification.setEnabled(true);
            } else {
                btn_15qualification.setEnabled(false);
            }

            if (backupNRestore == 1) {
                btn_16backupNRestore.setEnabled(true);
            } else {
                btn_16backupNRestore.setEnabled(false);
            }
        }
    }

    private static void disableButtons(JButton... btn) {
        for (JButton b : btn) {
            b.setEnabled(false);
        }
    }
}
