/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.JDBC;
import Classes.ToolsClass;
import java.awt.Desktop;
import java.io.File;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Hasitha Udara
 */
public class RegistrationFee extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationFee
     */
    public RegistrationFee() {
        initComponents();
        Menu();
        new Classes.Commons().background(this, lbl_background);
        tcl.setStuPayInvoiceId(txt_registrationId);
        tcl.incomeId(incomeID);
        setAmount();
        txt_amount.setText(amount + "");
        txt_firstName.setText(SRfirstname);
        txt_lastName.setText(SRlastname);
        lbl_username.setText(Home.un);
        lbl_userType.setText(Home.ut);
        lbl_date.setText(new Classes.Commons().Date());
        new Classes.Commons().time(lbl_time);
    }

      //////------------Menu-----------//////

    void Menu() {
        try {
            popup_menu.setText("Menu");
            popup_help.setText("Help");
            popup_exit.setText("Exit");
            

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    
    
    JDBC db = new JDBC();
    ToolsClass tcl = new ToolsClass();
    private final String feetype = "Reg";
    static double amount;
    static int incomeID;
    static String employeeid, justToday;
    static GuardianRegistration guardian;

    //--Student reg details--//
    static String studentid, SRfirstname, SRlastname, SRsalutation, SRgender,
            SRschool, SRno, SRstreet1, SRstreet2, SRcity, SRmobileNumber, SRstat, SRbirthday;

    //--End of student reg details--//
    //--Guardian reg details--//
    static String GRsalutation, GRfname, GRlname, GRtype, GRguardianid;
    static int GRmobile, GRlandno;
    //--End of Guardian reg details--//
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        popup_menu = new javax.swing.JMenuItem();
        popup_exit = new javax.swing.JMenuItem();
        popup_help = new javax.swing.JMenuItem();
        pnl_background = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        lbl_userType = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_registrationFee = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        lbl_lastName = new javax.swing.JLabel();
        lbl_amount = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_registrationId = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        lbl_firstName = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        popup_menu.setText("jMenuItem1");
        popup_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menuActionPerformed(evt);
            }
        });
        popupMenu.add(popup_menu);

        popup_exit.setText("jMenuItem2");
        popup_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_exitActionPerformed(evt);
            }
        });
        popupMenu.add(popup_exit);

        popup_help.setText("jMenuItem1");
        popup_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_helpActionPerformed(evt);
            }
        });
        popupMenu.add(popup_help);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));
        pnl_background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_backgroundMouseClicked(evt);
            }
        });
        pnl_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_header.setBackground(new java.awt.Color(255, 255, 255));
        pnl_header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_headerMouseClicked(evt);
            }
        });
        pnl_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 16, 20));

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        pnl_header.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 32, 32));

        lbl_userType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_userType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_userType.setText("User type");
        pnl_header.add(lbl_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 220, 20));

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_username.setText("Username");
        pnl_header.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 220, 30));

        lbl_time.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_time.setText("jLabel3");
        pnl_header.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 23, 100, -1));

        lbl_date.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_date.setText("jLabel3");
        pnl_header.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Registration Fee");
        pnl_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 340, 30));

        pnl_background.add(pnl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pnl_registrationFee.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration Fee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_registrationFee.setOpaque(false);
        pnl_registrationFee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_registrationFeeMouseClicked(evt);
            }
        });

        lbl_id.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_id.setText("Registration ID:");

        lbl_lastName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_lastName.setText("Last Name:");

        lbl_amount.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_amount.setText("Amount:");

        txt_amount.setEditable(false);
        txt_amount.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_amount.setEnabled(false);
        txt_amount.setOpaque(false);

        txt_lastName.setEditable(false);
        txt_lastName.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_lastName.setEnabled(false);
        txt_lastName.setOpaque(false);
        txt_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastNameActionPerformed(evt);
            }
        });

        txt_registrationId.setEditable(false);
        txt_registrationId.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_registrationId.setEnabled(false);
        txt_registrationId.setOpaque(false);
        txt_registrationId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registrationIdActionPerformed(evt);
            }
        });

        txt_firstName.setEditable(false);
        txt_firstName.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_firstName.setEnabled(false);
        txt_firstName.setOpaque(false);

        lbl_firstName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_firstName.setText("First Name:");

        btn_save.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_refresh.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_registrationFeeLayout = new javax.swing.GroupLayout(pnl_registrationFee);
        pnl_registrationFee.setLayout(pnl_registrationFeeLayout);
        pnl_registrationFeeLayout.setHorizontalGroup(
            pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrationFeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_registrationFeeLayout.createSequentialGroup()
                        .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_registrationFeeLayout.createSequentialGroup()
                                .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_lastName)
                                    .addComponent(lbl_firstName))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_registrationFeeLayout.createSequentialGroup()
                                .addComponent(lbl_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                            .addComponent(txt_firstName)
                            .addComponent(txt_registrationId)
                            .addComponent(txt_amount)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registrationFeeLayout.createSequentialGroup()
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_registrationFeeLayout.setVerticalGroup(
            pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrationFeeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_registrationId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_firstName))
                .addGap(18, 18, 18)
                .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_lastName))
                .addGap(18, 18, 18)
                .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_amount)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_registrationFeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_refresh)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_background.add(pnl_registrationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 710, -1));

        lbl_background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_background.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 360));

        getContentPane().add(pnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        refreshFields();
        txt_firstName.setText(SRfirstname);
        txt_lastName.setText(SRlastname);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        studentPayInvoice();
//        genarateReport();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        new Menu().setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void txt_registrationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registrationIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registrationIdActionPerformed

    private void popup_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menuActionPerformed
       this.dispose();
       new Menu().setVisible(true);
    }//GEN-LAST:event_popup_menuActionPerformed

    private void popup_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_exitActionPerformed
       this.dispose();
    }//GEN-LAST:event_popup_exitActionPerformed

    private void pnl_backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_backgroundMouseClicked
        if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_backgroundMouseClicked

    private void pnl_headerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_headerMouseClicked
        if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_headerMouseClicked

    private void pnl_registrationFeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_registrationFeeMouseClicked
       if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_registrationFeeMouseClicked

    private void popup_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_helpActionPerformed
       try {
            Desktop.getDesktop().open(new File("E:\\Syndicate\\Documentation\\General – Student Registration.pdf"));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_popup_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_registrationFee;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem popup_exit;
    private javax.swing.JMenuItem popup_help;
    private javax.swing.JMenuItem popup_menu;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_registrationId;
    // End of variables declaration//GEN-END:variables
    //--Student Registration Fee Invoice--//
    private void studentPayInvoice() {
        try {
            setEmployeeId();

            String thisTime = new SimpleDateFormat("HH:mm").format(new Date());
            ResultSet rs = db.getData("SELECT guardion_id FROM guardion_details WHERE guardion_id='" + GRguardianid + "'");
            
            if (rs.next()) {

                //--Saving Student to Database--// 
                db.putData("INSERT INTO student_reg (student_id, f_name, l_name, school, birthday, mobile_no, no, street1, street2, city, date, status, salutation_id, gender_id, guardion_id, emp_id) VALUES "
                        + "('" + studentid + "','" + SRfirstname + "','" + SRlastname + "','" + SRschool + "' ,'" + SRbirthday + "'  ,'" + SRmobileNumber + "','" + SRno + "' ,'" + SRstreet1 + "',"
                        + "'" + SRstreet2 + "'  ,'" + SRcity + "','" + justToday + "'  ,'" + SRstat + "','" + SRsalutation + "','" + SRgender + "','" + GRguardianid + "','" + employeeid + "'  )");
                //--End of Saving to Database--//

                //--Save to student_payment_invoice--//
                db.putData("INSERT INTO student_payment_invoice (student_invoice_id, date, amount, type, student_id) VALUES ('" + txt_registrationId.getText() + "',"
                        + "'" + justToday + "','" + amount + "','" + feetype + "','" + studentid + "')");
                //--End of saving student_payment_invoice--//

                //--Save to income--//
                db.putData("INSERT INTO income (income_id, date, time,amount, emp_id, student_invoice_id) VALUES "
                        + "('" + incomeID + "','" + justToday + "','" + thisTime + "','" + amount + "','" + employeeid + "','" + txt_registrationId.getText() + "')");
                this.dispose();
                //--End of Saving income--//
            } else {
                
                //--Saving Guardian to the Database--//
                db.putData("INSERT INTO guardion_details (guardion_id, f_name, l_name, type, mobile_no, home_no, salutation_id) VALUES "
                        + "('" + GRguardianid + "','" + GRfname + "','" + GRlname + "',"
                        + "'" + GRtype + "','" + GRmobile + "','" + GRlandno + "','" + GRsalutation + "')");
                //--Saving Guardian to the Database--//

                //--Saving Student to Database--// 
                db.putData("INSERT INTO student_reg (student_id, f_name, l_name, school, birthday, mobile_no, no, street1, street2, city, date, status, salutation_id, gender_id, guardion_id, emp_id) VALUES "
                        + "('" + studentid + "','" + SRfirstname + "','" + SRlastname + "','" + SRschool + "' ,'" + SRbirthday + "'  ,'" + SRmobileNumber + "','" + SRno + "' ,'" + SRstreet1 + "',"
                        + "'" + SRstreet2 + "'  ,'" + SRcity + "','" + justToday + "'  ,'" + SRstat + "','" + SRsalutation + "','" + SRgender + "','" + GRguardianid + "','" + employeeid + "'  )");
                //--End of Saving to Database--//

                //--Save to student_payment_invoice--//
                db.putData("INSERT INTO student_payment_invoice (student_invoice_id, date, amount, type, student_id) VALUES ('" + txt_registrationId.getText() + "',"
                        + "'" + justToday + "','" + amount + "','" + feetype + "','" + studentid + "')");
                //--End of saving student_payment_invoice--//

                //--Save to income--//
                db.putData("INSERT INTO income (income_id, date, time,amount, emp_id, student_invoice_id) VALUES "
                        + "('" + incomeID + "','" + justToday + "','" + thisTime + "','" + amount + "','" + employeeid + "','" + txt_registrationId.getText() + "')");
                this.dispose();
                guardian.dispose();
                //--End of Saving income--//
            }
            genarateReport();
            
        } catch (Exception ex) {
            System.out.println("Inside studentPayInvoice() " + ex);
            ex.printStackTrace();
        }
    }
    //--End of Student Registration Fee Invoice--//

    private void refreshFields() {
        tcl.incomeId(incomeID);
        txt_firstName.setText("");
        txt_lastName.setText("");
    }

    //--Setting amount--//
    private void setAmount() {
        try {
            ResultSet rs = db.getData("SELECT student_reg_fee FROM admin_panel");
            while (rs.next()) {
                amount = Double.parseDouble(rs.getString("student_reg_fee"));
            }
        } catch (Exception ex) {
            System.out.println("Inside setAmount method " + ex);
            ex.printStackTrace();
        }
    }
    //--End of Setting amount--//

    //Genarate Report
    void genarateReport() {
        String company_email = null, company_number = null;

        try {
            ResultSet rs = db.getData("SELECT company_email,company_mobile,company_office FROM admin_panel");
            while (rs.next()) {
                company_email = rs.getString("company_email");
                company_number = rs.getString("company_mobile") + " " + rs.getString("company_office");

            }
        } catch (Exception e) {
            System.out.println("in btn student registration genarate Report in class income details ");
            e.printStackTrace();
        }
        try {
            InputStream is = this.getClass().getClassLoader().getResourceAsStream("\\Reports\\classRegidtrationReport.jrxml");
            JasperDesign jd = JRXmlLoader.load(is);
            JasperReport jr = JasperCompileManager.compileReport(jd);

            Map<String, Object> p = new HashMap<String, Object>();
            p.put("email", company_email);
            p.put("numbers", company_number);
            p.put("Date", new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
            p.put("StudentID", studentid);
            p.put("StudentName", txt_firstName.getText() + " " + txt_lastName.getText());
            p.put("InvoiceID", txt_registrationId.getText());
            p.put("Amount", txt_amount.getText());
            p.put("FullAmount", txt_amount.getText());

            JasperPrint jp = JasperFillManager.fillReport(jr, p, new JREmptyDataSource());
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            System.out.println("in genarateReport method in class RegistrationFee");
            e.printStackTrace();
        }
    }

    //--End of Genarating 
//--Get EmployeeId--//
    private void setEmployeeId() {
        try {
            ResultSet rs = db.getData("SELECT emp_id FROM login WHERE user_name = '" + lbl_username.getText() + "'");

            while (rs.next()) {

                System.out.println("Got a result set");

                if (rs.getString("emp_id").toString().equals("")) {
                    System.out.println("Empty");
                } else {
                    employeeid = rs.getString("emp_id");
                    System.out.println(employeeid);
                }
            }
        } catch (Exception ex) {
            System.out.println("Inside setEmployeeId()" + ex);
            ex.printStackTrace();
        }
    }
//--End of Getting EmployeeId--//
}
