/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.JDBC;
import java.awt.Desktop;
import java.io.File;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinusha
 */
public class ResetPassword extends javax.swing.JFrame {

    private String typeID;
    private int recId;
    Home home;
    /**
     * Creates new form UserRejistration
     */
    public ResetPassword() {
        initComponents();
        Menu();
        lbl_username.setText(GUI.Home.un);
        lbl_userType.setText(GUI.Home.ut);
        new Classes.Commons().background(this, lbl_background);
        btn_submit.setEnabled(false);
        lbl_date.setText(new Classes.Commons().Date());
        new Classes.Commons().time(lbl_time);
    }
    
      //////------------Menu-----------//////

    void Menu() {
        try {
            popup_menu.setText("Menu");
            popup_help.setText("Help");
            popup_exit.setText("Exit");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    public ResetPassword(Home Home) {
        initComponents();
        home=Home;
                
        lbl_username.setText(GUI.Home.un);
        lbl_userType.setText(GUI.Home.ut);
        new Classes.Commons().background(this, lbl_background);
        btn_submit.setEnabled(false);
        lbl_date.setText(new Classes.Commons().Date());
        new Classes.Commons().time(lbl_time);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupMenu = new javax.swing.JPopupMenu();
        popup_menu = new javax.swing.JMenuItem();
        popup_help = new javax.swing.JMenuItem();
        popup_exit = new javax.swing.JMenuItem();
        pnl_UsrRegheader = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        lbl_userType = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_UserRegDetails = new javax.swing.JPanel();
        Lbl_UsrRegUsrNme = new javax.swing.JLabel();
        lbl_availability = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_confirmPassword = new javax.swing.JPasswordField();
        Lbl_UsrRegCnfrmPsswrd = new javax.swing.JLabel();
        Lbl_UsrRegUsrPsswrd1 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        txt_oldPassword = new javax.swing.JPasswordField();
        lbl_background = new javax.swing.JLabel();

        popup_menu.setText("jMenuItem1");
        popup_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menuActionPerformed(evt);
            }
        });
        popupMenu.add(popup_menu);

        popup_help.setText("jMenuItem2");
        popup_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_helpActionPerformed(evt);
            }
        });
        popupMenu.add(popup_help);

        popup_exit.setText("jMenuItem3");
        popup_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_exitActionPerformed(evt);
            }
        });
        popupMenu.add(popup_exit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_UsrRegheader.setBackground(new java.awt.Color(255, 255, 255));
        pnl_UsrRegheader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_UsrRegheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_UsrRegheaderMouseClicked(evt);
            }
        });
        pnl_UsrRegheader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_UsrRegheader.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 16, 16));

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_UsrRegheader.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 32, 32));

        lbl_userType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_userType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_userType.setText("User Type");
        pnl_UsrRegheader.add(lbl_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 220, -1));

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_username.setText("Username");
        pnl_UsrRegheader.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, -1));

        lbl_date.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_date.setText("jLabel3");
        pnl_UsrRegheader.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        lbl_time.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_time.setText("jLabel3");
        pnl_UsrRegheader.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 23, 100, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Reset");
        pnl_UsrRegheader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 340, 30));

        getContentPane().add(pnl_UsrRegheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        pnl_UserRegDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Registration Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_UserRegDetails.setOpaque(false);
        pnl_UserRegDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_UserRegDetailsMouseClicked(evt);
            }
        });

        Lbl_UsrRegUsrNme.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegUsrNme.setText("Old Password:");

        lbl_availability.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        txt_confirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_confirmPasswordKeyReleased(evt);
            }
        });

        Lbl_UsrRegCnfrmPsswrd.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegCnfrmPsswrd.setText("Confirme Password:");

        Lbl_UsrRegUsrPsswrd1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegUsrPsswrd1.setText("New Password:");

        btn_submit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_UserRegDetailsLayout = new javax.swing.GroupLayout(pnl_UserRegDetails);
        pnl_UserRegDetails.setLayout(pnl_UserRegDetailsLayout);
        pnl_UserRegDetailsLayout.setHorizontalGroup(
            pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserRegDetailsLayout.createSequentialGroup()
                .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_UserRegDetailsLayout.createSequentialGroup()
                        .addGap(609, 609, 609)
                        .addComponent(lbl_availability, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_UserRegDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_submit)
                            .addGroup(pnl_UserRegDetailsLayout.createSequentialGroup()
                                .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_UserRegDetailsLayout.createSequentialGroup()
                                        .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lbl_UsrRegUsrPsswrd1)
                                            .addComponent(Lbl_UsrRegCnfrmPsswrd))
                                        .addGap(32, 32, 32))
                                    .addGroup(pnl_UserRegDetailsLayout.createSequentialGroup()
                                        .addComponent(Lbl_UsrRegUsrNme)
                                        .addGap(78, 78, 78)))
                                .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_oldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_confirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                        .addComponent(txt_password)))))))
                .addGap(70, 70, 70))
        );
        pnl_UserRegDetailsLayout.setVerticalGroup(
            pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_UserRegDetailsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_UsrRegUsrNme)
                    .addComponent(txt_oldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_UsrRegUsrPsswrd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_UserRegDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_UsrRegCnfrmPsswrd))
                .addGap(18, 18, 18)
                .addComponent(btn_submit)
                .addGap(44, 44, 44)
                .addComponent(lbl_availability, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnl_UserRegDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, 190));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        lbl_background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 250));

        setSize(new java.awt.Dimension(430, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_confirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confirmPasswordKeyReleased
        String pw = new String(txt_password.getPassword());
        String cpw = new String(txt_confirmPassword.getPassword());

        if (pw.equals(cpw)) {
            btn_submit.setEnabled(true);
        } else {
            btn_submit.setEnabled(false);
        }
    }//GEN-LAST:event_txt_confirmPasswordKeyReleased

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        resetPassword();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void popup_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menuActionPerformed
       this.dispose();
       new Menu().setVisible(true);
    }//GEN-LAST:event_popup_menuActionPerformed

    private void popup_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_helpActionPerformed
      try {
            Desktop.getDesktop().open(new File("E:\\Syndicate\\Documentation\\General – Reset Password.pdf"));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_popup_helpActionPerformed

    private void popup_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_exitActionPerformed
       this.dispose();
    }//GEN-LAST:event_popup_exitActionPerformed

    private void pnl_UsrRegheaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_UsrRegheaderMouseClicked
       if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_UsrRegheaderMouseClicked

    private void pnl_UserRegDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_UserRegDetailsMouseClicked
       if (evt.getButton() == 3) {
            popupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_pnl_UserRegDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_UsrRegCnfrmPsswrd;
    private javax.swing.JLabel Lbl_UsrRegUsrNme;
    private javax.swing.JLabel Lbl_UsrRegUsrPsswrd1;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_availability;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_UserRegDetails;
    private javax.swing.JPanel pnl_UsrRegheader;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem popup_exit;
    private javax.swing.JMenuItem popup_help;
    private javax.swing.JMenuItem popup_menu;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JPasswordField txt_oldPassword;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
void resetPassword() {
        String opw = new String(txt_oldPassword.getPassword());
        String cpw = new String(txt_confirmPassword.getPassword());
        String un = lbl_username.getText();

        try {
            ResultSet rs = new JDBC().getData("SELECT user_name, password FROM login WHERE user_name='" + un + "' AND password='" + opw + "'");

            if (rs.next()) {
                String usn = rs.getString("user_name");
                String pw = rs.getString("password");

                if (un.equals(usn) && opw.equals(pw)) {
                    new JDBC().putData("UPDATE login SET password='" + cpw + "' WHERE user_name='" + un + "'");
                    JOptionPane.showMessageDialog(this, "Password Successfully changed.\nPlease login again.");
                }
                this.dispose();
                home.dispose();
                new Login.Login().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect password.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
