/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.JDBC;
import java.awt.Desktop;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
/**
 *
 * @author Dinusha
 */
public class UserRegistration extends javax.swing.JFrame {

    private String typeID;
    private int recId;

    /**
     * Creates new form UserRejistration
     */
    Logger log=Logger.getLogger("User Registration");
    public UserRegistration() {
        initComponents();
        Menu();
        lbl_username.setText(GUI.Home.un);
        lbl_userType.setText(GUI.Home.ut);
        rad_teacher.setSelected(true);
        cmb_userType.setSelectedItem("Teacher");
        btn_submit.setEnabled(false);
        rad_admin.setVisible(false);
        lbl_date.setText(new Classes.Commons().Date());
        new Classes.Commons().time(lbl_time);
        cmb_userType.setEnabled(false);
        loadCombo();
        checkUser();
    }
    
    void Menu(){
        popup_menu.setText("Menu");
        popup_help.setText("Help");
        popup_exit.setText("Exit");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        popup_menu = new javax.swing.JMenuItem();
        popup_help = new javax.swing.JMenuItem();
        popup_exit = new javax.swing.JMenuItem();
        pnl_UsrRegheader = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        lbl_userType = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_UsrRegsearch = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        rad_teacher = new javax.swing.JRadioButton();
        rad_employee = new javax.swing.JRadioButton();
        rad_admin = new javax.swing.JRadioButton();
        pnl_UserRegDetails = new javax.swing.JPanel();
        Lbl_UsrRegUsrNme = new javax.swing.JLabel();
        lbl_availability = new javax.swing.JLabel();
        Lbl_UsrRegType = new javax.swing.JLabel();
        cmb_userType = new javax.swing.JComboBox();
        txt_userName = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_confirmPassword = new javax.swing.JPasswordField();
        Lbl_UsrRegCnfrmPsswrd = new javax.swing.JLabel();
        Lbl_UsrRegEmplyNme = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        Lbl_ExpenceID2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        Lbl_UsrRegUsrPsswrd1 = new javax.swing.JLabel();
        pnl_Recoverydetails = new javax.swing.JPanel();
        btn_Expncerefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Lbl_UsrRegQuestion1 = new javax.swing.JLabel();
        Lbl_UsrRegQuestion2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_qtn1 = new javax.swing.JTextField();
        txt_ans1 = new javax.swing.JTextField();
        txt_qtn2 = new javax.swing.JTextField();
        txt_ans2 = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        popup_menu.setText("jMenuItem1");
        popup_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_menuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popup_menu);

        popup_help.setText("jMenuItem2");
        popup_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_helpActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popup_help);

        popup_exit.setText("jMenuItem3");
        popup_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup_exitActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popup_exit);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_UsrRegheader.setBackground(new java.awt.Color(255, 255, 255));
        pnl_UsrRegheader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_UsrRegheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_UsrRegheaderMouseClicked(evt);
            }
        });
        pnl_UsrRegheader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_UsrRegheader.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 16, 16));

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_UsrRegheader.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 32, 32));

        lbl_userType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_userType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_userType.setText("User Type");
        pnl_UsrRegheader.add(lbl_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 220, -1));

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_username.setText("Username");
        pnl_UsrRegheader.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 220, -1));

        lbl_date.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_date.setText("jLabel3");
        pnl_UsrRegheader.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        lbl_time.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_time.setText("jLabel3");
        pnl_UsrRegheader.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 23, 100, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("User Registration");
        pnl_UsrRegheader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 340, 30));

        getContentPane().add(pnl_UsrRegheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 50));

        pnl_UsrRegsearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_UsrRegsearch.setOpaque(false);
        pnl_UsrRegsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_UsrRegsearchMouseClicked(evt);
            }
        });
        pnl_UsrRegsearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_search.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnl_UsrRegsearch.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1190, 29));

        btn_search.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        pnl_UsrRegsearch.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 70, 154, 27));

        buttonGroup1.add(rad_teacher);
        rad_teacher.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rad_teacher.setText("Teacher");
        rad_teacher.setOpaque(false);
        rad_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_teacherActionPerformed(evt);
            }
        });
        pnl_UsrRegsearch.add(rad_teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        buttonGroup1.add(rad_employee);
        rad_employee.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rad_employee.setText("Employee");
        rad_employee.setOpaque(false);
        rad_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_employeeActionPerformed(evt);
            }
        });
        pnl_UsrRegsearch.add(rad_employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        buttonGroup1.add(rad_admin);
        rad_admin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rad_admin.setText("Admin");
        rad_admin.setOpaque(false);
        rad_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_adminActionPerformed(evt);
            }
        });
        pnl_UsrRegsearch.add(rad_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        getContentPane().add(pnl_UsrRegsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1366, 120));

        pnl_UserRegDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Registration Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_UserRegDetails.setOpaque(false);
        pnl_UserRegDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_UserRegDetailsMouseClicked(evt);
            }
        });
        pnl_UserRegDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_UsrRegUsrNme.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegUsrNme.setText("User Name:");
        pnl_UserRegDetails.add(Lbl_UsrRegUsrNme, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 213, -1, -1));

        lbl_availability.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        pnl_UserRegDetails.add(lbl_availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 210, 29, 29));

        Lbl_UsrRegType.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegType.setText("Type:");
        pnl_UserRegDetails.add(Lbl_UsrRegType, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 166, -1, -1));

        cmb_userType.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmb_userType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_userTypeKeyReleased(evt);
            }
        });
        pnl_UserRegDetails.add(cmb_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 160, 419, 32));

        txt_userName.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userNameFocusLost(evt);
            }
        });
        txt_userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_userNameKeyReleased(evt);
            }
        });
        pnl_UserRegDetails.add(txt_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 210, 419, 29));
        pnl_UserRegDetails.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 257, 419, 29));

        txt_confirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_confirmPasswordKeyReleased(evt);
            }
        });
        pnl_UserRegDetails.add(txt_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 304, 419, 28));

        Lbl_UsrRegCnfrmPsswrd.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegCnfrmPsswrd.setText("Confirme Password:");
        pnl_UserRegDetails.add(Lbl_UsrRegCnfrmPsswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 305, -1, -1));

        Lbl_UsrRegEmplyNme.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegEmplyNme.setText("Name:");
        pnl_UserRegDetails.add(Lbl_UsrRegEmplyNme, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 116, -1, -1));

        txt_name.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        pnl_UserRegDetails.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 113, 419, 29));

        Lbl_ExpenceID2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_ExpenceID2.setText("Employee/Teacher ID:");
        pnl_UserRegDetails.add(Lbl_ExpenceID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 69, -1, -1));

        txt_id.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        pnl_UserRegDetails.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 66, 419, 29));

        Lbl_UsrRegUsrPsswrd1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegUsrPsswrd1.setText("User Password:");
        pnl_UserRegDetails.add(Lbl_UsrRegUsrPsswrd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 258, -1, -1));

        getContentPane().add(pnl_UserRegDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 660, 350));

        pnl_Recoverydetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recovery Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_Recoverydetails.setOpaque(false);
        pnl_Recoverydetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_RecoverydetailsMouseClicked(evt);
            }
        });

        btn_Expncerefresh.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_Expncerefresh.setText("Refresh");
        btn_Expncerefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Answer 1:");

        Lbl_UsrRegQuestion1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegQuestion1.setText("Question 1:");

        Lbl_UsrRegQuestion2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Lbl_UsrRegQuestion2.setText("Question 2:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("Answer 2:");

        txt_qtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtn1ActionPerformed(evt);
            }
        });

        txt_ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ans1ActionPerformed(evt);
            }
        });

        txt_qtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtn2ActionPerformed(evt);
            }
        });

        txt_ans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ans2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_RecoverydetailsLayout = new javax.swing.GroupLayout(pnl_Recoverydetails);
        pnl_Recoverydetails.setLayout(pnl_RecoverydetailsLayout);
        pnl_RecoverydetailsLayout.setHorizontalGroup(
            pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RecoverydetailsLayout.createSequentialGroup()
                .addGap(708, 708, 708)
                .addComponent(btn_Expncerefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl_RecoverydetailsLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnl_RecoverydetailsLayout.createSequentialGroup()
                        .addComponent(Lbl_UsrRegQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txt_qtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_RecoverydetailsLayout.createSequentialGroup()
                        .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RecoverydetailsLayout.createSequentialGroup()
                                .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Lbl_UsrRegQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(pnl_RecoverydetailsLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ans2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                            .addComponent(txt_qtn2)
                            .addComponent(txt_ans1)))))
        );
        pnl_RecoverydetailsLayout.setVerticalGroup(
            pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RecoverydetailsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_UsrRegQuestion1))
                .addGap(18, 18, 18)
                .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ans1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_UsrRegQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnl_RecoverydetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(373, 373, 373)
                .addComponent(btn_Expncerefresh))
        );

        getContentPane().add(pnl_Recoverydetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 178, 700, 350));

        btn_submit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 550, 140, 30));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        lbl_background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_qtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtn2ActionPerformed

    private void txt_ans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ans2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ans2ActionPerformed

    private void txt_ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ans1ActionPerformed

    private void txt_qtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtn1ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        search();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        submit();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_confirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confirmPasswordKeyReleased
        String pw = new String(txt_password.getPassword());
        String cpw = new String(txt_confirmPassword.getPassword());

        if (pw.equals(cpw)) {
            btn_submit.setEnabled(true);
        } else {
            btn_submit.setEnabled(false);
        }
    }//GEN-LAST:event_txt_confirmPasswordKeyReleased

    private void txt_userNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userNameKeyReleased
        checkAvailability();
        if (txt_userName.getText().isEmpty()) {
            lbl_availability.setIcon(null);
        }
    }//GEN-LAST:event_txt_userNameKeyReleased

    private void txt_userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userNameFocusLost

    }//GEN-LAST:event_txt_userNameFocusLost

    private void cmb_userTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_userTypeKeyReleased
        int i = evt.getKeyCode();

        if (i == 10) {
            txt_userName.grabFocus();
        }
    }//GEN-LAST:event_cmb_userTypeKeyReleased

    private void rad_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_adminActionPerformed
        txt_search.setEnabled(false);
        txt_id.setEnabled(false);
        txt_name.setEnabled(false);
        btn_search.setEnabled(false);
        cmb_userType.setSelectedItem("Admin");
    }//GEN-LAST:event_rad_adminActionPerformed

    private void rad_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_employeeActionPerformed
        txt_search.setEnabled(true);
        txt_id.setEnabled(true);
        txt_name.setEnabled(true);
        btn_search.setEnabled(true);
        cmb_userType.setSelectedItem("Employee");
    }//GEN-LAST:event_rad_employeeActionPerformed

    private void rad_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_teacherActionPerformed
        txt_search.setEnabled(true);
        txt_id.setEnabled(true);
        txt_name.setEnabled(true);
        btn_search.setEnabled(true);
        cmb_userType.setSelectedItem("Teacher");
    }//GEN-LAST:event_rad_teacherActionPerformed

    private void popup_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_helpActionPerformed
   try {
            Desktop.getDesktop().open(new File("E:\\Syndicate\\Documentation\\General - User Registration.pdf"));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_popup_helpActionPerformed

    private void popup_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_popup_exitActionPerformed

    private void popup_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup_menuActionPerformed
        this.dispose();
      new Menu().setVisible(true);
    }//GEN-LAST:event_popup_menuActionPerformed

    private void pnl_UsrRegheaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_UsrRegheaderMouseClicked
     if (evt.getButton()==3) {
            jPopupMenu1.show(this, evt.getX() ,evt.getY());
        }
    }//GEN-LAST:event_pnl_UsrRegheaderMouseClicked

    private void pnl_UsrRegsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_UsrRegsearchMouseClicked
       if (evt.getButton()==3) {
            jPopupMenu1.show(this, evt.getX() ,evt.getY());
        }
    }//GEN-LAST:event_pnl_UsrRegsearchMouseClicked

    private void pnl_UserRegDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_UserRegDetailsMouseClicked
       if (evt.getButton()==3) {
            jPopupMenu1.show(this, evt.getX() ,evt.getY());
        }
    }//GEN-LAST:event_pnl_UserRegDetailsMouseClicked

    private void pnl_RecoverydetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_RecoverydetailsMouseClicked
        if (evt.getButton()==3) {
            jPopupMenu1.show(this, evt.getX() ,evt.getY());
        }
    }//GEN-LAST:event_pnl_RecoverydetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_ExpenceID2;
    private javax.swing.JLabel Lbl_UsrRegCnfrmPsswrd;
    private javax.swing.JLabel Lbl_UsrRegEmplyNme;
    private javax.swing.JLabel Lbl_UsrRegQuestion1;
    private javax.swing.JLabel Lbl_UsrRegQuestion2;
    private javax.swing.JLabel Lbl_UsrRegType;
    private javax.swing.JLabel Lbl_UsrRegUsrNme;
    private javax.swing.JLabel Lbl_UsrRegUsrPsswrd1;
    private javax.swing.JButton btn_Expncerefresh;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmb_userType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbl_availability;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_Recoverydetails;
    private javax.swing.JPanel pnl_UserRegDetails;
    private javax.swing.JPanel pnl_UsrRegheader;
    private javax.swing.JPanel pnl_UsrRegsearch;
    private javax.swing.JMenuItem popup_exit;
    private javax.swing.JMenuItem popup_help;
    private javax.swing.JMenuItem popup_menu;
    private javax.swing.JRadioButton rad_admin;
    private javax.swing.JRadioButton rad_employee;
    private javax.swing.JRadioButton rad_teacher;
    private javax.swing.JTextField txt_ans1;
    private javax.swing.JTextField txt_ans2;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_qtn1;
    private javax.swing.JTextField txt_qtn2;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
    void search() {
        if (rad_teacher.isSelected()) {
            try {
                ResultSet rs = new Classes.JDBC().getData("SELECT * FROM teacher_reg WHERE nic='" + txt_search.getText() + "'");

                if (rs.next()) {
                    String fname = rs.getString("f_name");
                    String lname = rs.getString("l_name");
                    String id = rs.getString("teacher_id");

                    txt_id.setText(id);
                    txt_name.setText(fname + " " + lname);
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect NIC. Please check and enter again");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (rad_employee.isSelected()) {
            try {
                ResultSet rs = new Classes.JDBC().getData("SELECT * FROM employee_reg WHERE nic='" + txt_search.getText() + "'");

                while (rs.next()) {
                    String fname = rs.getString("f_name");
                    String lname = rs.getString("l_name");
                    String id = rs.getString("emp_id");

                    txt_id.setText(id);
                    txt_name.setText(fname + " " + lname);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        loadCombo();
    }

    void loadCombo() {
        try {
            ResultSet re = new JDBC().getData("select * from user_type");
            Vector ve = new Vector();
            while (re.next()) {
                ve.add(re.getString("user_type"));
            }
            cmb_userType.setModel(new DefaultComboBoxModel(ve));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void submit() {
        if (rad_teacher.isSelected()) {
            try {
                new JDBC().putData("INSERT INTO recovery(quaction1, quaction2, answar1, answar2)VALUES"
                        + "('" + txt_qtn1.getText() + "',"
                        + "'" + txt_qtn2.getText() + "',"
                        + "'" + txt_ans1.getText() + "',"
                        + "'" + txt_ans2.getText() + "')");

                ResultSet rs1 = new JDBC().getData("SELECT MAX(recovery_id) FROM recovery");
                ResultSet rs2 = new JDBC().getData("SELECT user_type_id FROM user_type WHERE user_type='" + cmb_userType.getSelectedItem() + "'");

                while (rs1.next()) {
                    recId = rs1.getInt(1);
                }

                while (rs2.next()) {
                    typeID = rs2.getString("user_type_id");
                }

                String pw = new String(txt_confirmPassword.getPassword());

                new JDBC().putData("INSERT INTO login(user_name, password, system_id, user_type_id, recovery_id, teacher_id)VALUES"
                        + "('" + txt_userName.getText() + "',"
                        + "'" + pw + "',"
                        + "'" + txt_id.getText() + "',"
                        + "'" + typeID + "',"
                        + "'" + recId + "',"
                        + "'" + txt_id.getText() + "')");
                
                log.info("User Name :"+txt_userName.getText()+"User Registerd at :"+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (rad_employee.isSelected()) {
            try {
                new JDBC().putData("INSERT INTO recovery(quaction1, quaction2, answar1, answar2)VALUES"
                        + "('" + txt_qtn1.getText() + "',"
                        + "'" + txt_qtn2.getText() + "',"
                        + "'" + txt_ans1.getText() + "',"
                        + "'" + txt_ans2.getText() + "')");

                ResultSet rs1 = new JDBC().getData("SELECT MAX(recovery_id) FROM recovery");
                ResultSet rs2 = new JDBC().getData("SELECT user_type_id FROM user_type WHERE user_type='" + cmb_userType.getSelectedItem() + "'");

                while (rs1.next()) {
                    recId = rs1.getInt(1);
                }

                while (rs2.next()) {
                    typeID = rs2.getString("user_type_id");
                }

                String pw = new String(txt_confirmPassword.getPassword());

                new JDBC().putData("INSERT INTO login(user_name, password, system_id, user_type_id, recovery_id, emp_id)VALUES"
                        + "('" + txt_userName.getText() + "',"
                        + "'" + pw + "',"
                        + "'" + txt_id.getText() + "',"
                        + "'" + typeID + "',"
                        + "'" + recId + "',"
                        + "'" + txt_id.getText() + "')");
                log.info("User Name :"+txt_userName.getText()+"User Registerd at :"+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (rad_admin.isSelected()) {

            String utype = "Admin";

            try {
                new JDBC().putData("INSERT INTO recovery(quaction1, quaction2, answar1, answar2)VALUES"
                        + "('" + txt_qtn1.getText() + "',"
                        + "'" + txt_qtn2.getText() + "',"
                        + "'" + txt_ans1.getText() + "',"
                        + "'" + txt_ans2.getText() + "')");

                ResultSet rs1 = new JDBC().getData("SELECT MAX(recovery_id) FROM recovery");
                ResultSet rs2 = new JDBC().getData("SELECT user_type_id FROM user_type WHERE user_type='" + utype + "'");

                while (rs1.next()) {
                    recId = rs1.getInt(1);
                }

                while (rs2.next()) {
                    typeID = rs2.getString("user_type_id");
                }

                String pw = new String(txt_confirmPassword.getPassword());

                new JDBC().putData("INSERT INTO login(user_name, password, system_id, user_type_id, recovery_id)VALUES"
                        + "('" + txt_userName.getText() + "',"
                        + "'" + pw + "',"
                        + "'" + typeID + "',"
                        + "'" + typeID + "',"
                        + "'" + recId + "')");
                log.info("User Name :"+txt_userName.getText()+"User Registerd at :"+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
            } catch (Exception ex) {
               ex.printStackTrace();
            }
        }

        JOptionPane.showMessageDialog(this, "Saved.....!");
    }

    void checkAvailability() {
        String un = txt_userName.getText();

        try {
            ResultSet rs = new JDBC().getData("SELECT user_name FROM login WHERE user_name='" + un + "'");

            if (rs.next()) {
                lbl_availability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wrong.png")));
                lbl_availability.setToolTipText("This username already taken.");
            } else {
                lbl_availability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png")));
                lbl_availability.setToolTipText("This username is available.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void checkUser() {
        String type = lbl_userType.getText();

        if (type.equals("Admin")) {
            rad_admin.setVisible(true);
        } else {
            rad_admin.setVisible(false);
        }
    }
}
