/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.security.MessageDigest;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Uditha N. Bandara
 */
public class EnterSecurityCode extends javax.swing.JFrame {

    /**
     * Creates new form PasswordRecovery
     */
    public EnterSecurityCode() {
        initComponents();
        new Classes.Commons().background(this, lbl_background);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setUndecorated(true);
        com.sun.awt.AWTUtilities.setWindowOpaque(this, false);
        lbl_username.setText(PasswordRecovery.u);
        lbl_hash.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background1 = new javax.swing.JPanel();
        pnl_background2 = new javax.swing.JPanel();
        pnl_enterSecurityCode = new javax.swing.JPanel();
        lbl_messagel1 = new javax.swing.JLabel();
        lbl_message2 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        txt_code = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();
        lbl_hash = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl_background1.setBackground(Classes.Commons.Transparent);
        pnl_background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_background2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        pnl_background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_enterSecurityCode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Security Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N
        pnl_enterSecurityCode.setOpaque(false);

        lbl_messagel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_messagel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_messagel1.setText("Check your email and enter the security code to reset");

        lbl_message2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_message2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_message2.setText("password");

        btn_clear.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_clear.setText("Clear");

        btn_next.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_next.setText("Next>>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        txt_code.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout pnl_enterSecurityCodeLayout = new javax.swing.GroupLayout(pnl_enterSecurityCode);
        pnl_enterSecurityCode.setLayout(pnl_enterSecurityCodeLayout);
        pnl_enterSecurityCodeLayout.setHorizontalGroup(
            pnl_enterSecurityCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_enterSecurityCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_enterSecurityCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_messagel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_message2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(txt_code))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_enterSecurityCodeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        pnl_enterSecurityCodeLayout.setVerticalGroup(
            pnl_enterSecurityCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_enterSecurityCodeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_messagel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbl_message2)
                .addGap(18, 18, 18)
                .addGroup(pnl_enterSecurityCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pnl_background2.add(pnl_enterSecurityCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, 180));

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_username.setText("Username");
        pnl_background2.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, 40));

        lbl_background.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        pnl_background2.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 270));

        lbl_hash.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lbl_hash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_hash.setText("Username");
        pnl_background2.add(lbl_hash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, 40));

        pnl_background1.add(pnl_background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 249, 440, 270));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelWhite.png"))); // NOI18N
        jButton1.setToolTipText("Close");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_background1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 16, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Classes.Commons.FadeOut(this);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        checkCode();
    }//GEN-LAST:event_btn_nextActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Classes.Commons.FadeIn(this);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterSecurityCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterSecurityCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterSecurityCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterSecurityCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterSecurityCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_hash;
    private javax.swing.JLabel lbl_message2;
    private javax.swing.JLabel lbl_messagel1;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_background1;
    private javax.swing.JPanel pnl_background2;
    private javax.swing.JPanel pnl_enterSecurityCode;
    private javax.swing.JTextField txt_code;
    // End of variables declaration//GEN-END:variables
    void checkCode() {
        try {
            String un = lbl_username.getText();
            String pw = txt_code.getText();

            ResultSet rs = new Classes.JDBC().getData("SELECT * FROM login WHERE user_name='" + un + "'");

            if (rs.next()) {
                String p = rs.getString("password");

                String original = p;
                MessageDigest md = MessageDigest.getInstance("MD5");
                md.update(original.getBytes());
                byte[] diegest = md.digest();
                StringBuffer sb = new StringBuffer();
                for (byte b : diegest) {
                    sb.append(String.format("%02x", b & 0xff));
                }
                
                String hash = sb.toString();
                
                lbl_hash.setText(hash);
                
                String getHash = lbl_hash.getText();

                if (pw.equals(getHash)) {
                    Classes.Commons.FadeOut(this);
                    this.dispose();
                    new ResetPassword().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong recovery code.");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
